### ISSUE TITLE
scroll reveal works on scroll up but not on scroll down

### ISSUE THREAD

**Issue by BendTheCode** [jlmakes/scrollreveal#111]
Hello,
I have an issue with scroll reveal when I scroll down, the animations don't play.

**Comment by interactionist** [comment]
Just give you some hints here as I had to debug this on latest Safari/Chrome:

If you have only intrinsic heights on your html/body and no height set AND have set ```viewport: window.document.documentElement```, the result of  ```sr.getViewportH()``` are not the viewport but the intrinsic height of the ```html```element.

To get this solved either use
```
html, body {

}

**Comment by connorbode** [comment]
@raphaelokon +1 thanks

**Comment by mahieddine** [comment]
Thank you !!

**Comment by MCarlson8198** [comment]
@raphaelokon Thank you!

**Comment by spacecowgoesmoo** [comment]
Thank you!

**Comment by sumitkalia** [comment]
Thank You

**Comment by shunyata** [comment]
Thanks 👍

**Comment by belgamo** [comment]
Nice, thanks!
