### ISSUE TITLE
Public method to remove ScrollReveal styles and event listeners

### ISSUE THREAD

**Issue by jgatjens** [jlmakes/scrollreveal#227]
I’m building a single-page application and Im using your awesome library for the homepage. When the user changes to another page, the DOM is removed by the router and I would like to ensure all events listener are removed as well to not have any memory leaks.

_Example:_

``` js
sr.destroy();
```

**Comment by jlmakes** [comment]
Hey @jgatjens,

The event listeners are on all containers—so `window` and any custom nodes passed into `config.container`. You can see this in the source on line 333:
```js
function _init(){
  if ( sr.supported() ){
    // Initial animate call triggers valid reveal animations on first load.
    // Subsequent animate calls are made inside the event handler.
    _animate();
    // Then we loop through all container nodes in the store and bind event
    // listeners to each.
    for ( var i = 0; i < sr.store.containers.length; i++ ){
      sr.store.containers[ i ].addEventListener( 'scroll', _handler );
      sr.store.containers[ i ].addEventListener( 'resize', _handler );
    }
    // Let’s also do a one-time binding of window event listeners.
    if ( !sr.initialized ){
      window.addEventListener( 'scroll', _handler );
      window.addEventListener( 'resize', _handler );
      sr.initialized = true;
    }
  }
  return sr;
}
```

For the time being, you can fork ScrollReveal and modify the source yourself by reversing the `init()` method—but make sure to add it to the prototype so it’s exposed publicly.

_Example:_
```js
ScrollReveal.prototype.destroy = function() {
  if ( sr.initialized ){
    for ( var i = 0; i < sr.store.containers.length; i++ ){
      sr.store.containers[ i ].removeEventListener( 'scroll', _handler );
      sr.store.containers[ i ].removeEventListener( 'resize', _handler );
    }
    window.removeEventListener( 'scroll', _handler );
    window.removeEventListener( 'resize', _handler );
    sr.initialized = false;
  }
  return sr;
}
```

Let me know how things work out. For now, I’ll icebox this for future a release.

Hope this helps! :bow:

**Comment by jgatjens** [comment]
Thank you :100:

**Comment by ElisabethStereosuper** [comment]
Hi @jlmakes , I need a destroy() method as well for the resize, but I can't get this code to work! Could you please explain a bit more where to put it and how to use it? Thanks!

**Comment by jlmakes** [comment]
@ElisabethStereosuper This is a modification to the source, so you will need to use the unminified version of `scrollreveal.js` and add the method described above, alongside the other methods on the prototype.

With the source modified, you will then be able to use `sr.destroy()` in your page scripts.

**Comment by ElisabethStereosuper** [comment]
Thanks for your quick answer! So I tried  that, I added the method line 139, and then called sr.destroy() on resize, but it doesn't seem to have any effect.. Have I missed something?

**Comment by jlmakes** [comment]
So the point of `sr.destroy()` detailed above is to remove ScrollReveal's event listeners, it has no impact on styles. For example, if you were loading new content asynchronously to display a new page and you didn't want the listeners sticking around on previous reveals.

@ElisabethStereosuper, it sounds like you just want ScrollReveal to "update" on resize, which is as simple as calling `sr.sync()`--this will call all previous `sr.reveal()` calls again, catching any new elements or styles.

**Comment by ElisabethStereosuper** [comment]
Well I also change the configuration of ScrollReveal on the resize (for example the direction).
But I tried the sync() method, and it doesn't seem to have any effect either..
For now I just set the reset to false, it solves the problem, but it's too bad I can't use it.
Thanks anyway for your help @jlmakes !

**Comment by relish27** [comment]
Would also like this addition!  Thank you.

**Comment by jlmakes** [comment]
@relish27 This has been available in the ScrollReveal v4 beta for a few months.

_ScrollReveal v4_
```js
sr.reveal('.triangles')
sr.reveal('.squares')
sr.reveal('.circles')

// we can remove styles/listeners from
// a specific element set like this:
sr.clean('.triangles')

// or remove them all, like this:
sr.destroy()
```

Check out what else is [different in v4](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md).
