### ISSUE TITLE
sequenced animation with dynamically added containers

### ISSUE THREAD

**Issue by krizz07** [jlmakes/scrollreveal#297]
Hello, I am using ScrollReveal with a slider plugin.

```html
<div class="slider-container">
  <div class="pabrik-slider">
    <div class="swiper-wrapper">

      <div class="swiper-slide">
        <div class="content"></div>  <!--element to be animated-->
      </div>

      <div class="swiper-slide">
        <div class="content"></div>  <!--element to be animated-->
      </div>

      <!--et al.-->

    </div>
  </div>
</div>
```
Right now, for revealing the `.content` on scroll, I am using this code:

```js
var config = {
    duration: 500,
    scale: 1,
    origin: 'bottom',
    viewOffset: { top: 60 }
};

sr.reveal(".content", config, 300);
```

It does animate as I scroll, but it also continues the animation until the last item.

As the `.slider-container` element count is dynamic, I've tried adding unique IDs to each `.swiper-wrapper` and customizing `config.container` but that doesn't work.

Is there any workaround? Thanks!

**Comment by jlmakes** [comment]
If I understand the problem correctly, this is a limitation of the animation sequencer at present: any element within a sequence that is visible, will trigger the entire sequence.

There is no built-in method to create reveals that wait for the previous element to reveal, but that only trigger when visible...

However, this has come up before in #272, and there you can find a [sample workaround](https://github.com/jlmakes/scrollreveal.js/issues/272#issuecomment-233368675).

**Comment by bjmiller121** [comment]
Here's another example of a workaround similar to https://github.com/jlmakes/scrollreveal/issues/272#issuecomment-233368675 but handling multiple revealed items per container and without the limitations of waiting for the previous animation to complete (using jQuery in the example, but could easily be rewritten with vanilla JS).

``` js
var sequenceInterval = 100;

window.sr = ScrollReveal();

// Custom reveal sequencing by container
$('.scroll-reveal__sequence-container').each(function() {
  var sequenceDelay = 0;
  $(this).find('.scroll-reveal--sequenced').each(function() {
    sr.reveal(this, {
      delay: sequenceDelay
    });

    sequenceDelay += sequenceInterval;
  });
});
```

``` html
<div class="scroll-reveal__sequence-container">
  <div class="scroll-reveal scroll-reveal--sequenced">
    Content
  </div>
  <div class="scroll-reveal scroll-reveal--sequenced">
    Content
  </div>
  <div class="scroll-reveal scroll-reveal--sequenced">
    Content
  </div>
  <div class="scroll-reveal scroll-reveal--sequenced">
    Content
  </div>
</div>
```

**Note:** Each item in the container should be in a row so they enter the viewport at the same time.

Adjust the `sequenceInterval` variable to change the gap between sequenced content

### [Live Demo on Codepen](http://codepen.io/bjmiller121/pen/EZWapQ)
