### ISSUE TITLE
Items scroll doesn't work like demo

### ISSUE THREAD

**Issue by snoopy15** [jlmakes/scrollreveal#299]
Hi there,

I'm trying to make same effect as your block demo on https://scrollrevealjs.org/ and I'm using same code, but it doesn't work like that. It doesn't show item by item, it shows whole items in same time.

This is how my script looks:

```js
var config = {
  viewFactor : 0.15,
  duration   : 800,
  distance   : "0px",
  scale      : 0.8
};

window.sr = ScrollReveal( config );

if (sr.isSupported()) {
  document.documentElement.classList.add('sr');
}
})();

sr.reveal( ".grid-items .item", { 
reset: true, 
viewOffset: { top: 64 }
});
```

You can take a look at my website: http://manoucher.com/lifestyle/

Thank you!

**Comment by jlmakes** [comment]
Please read more about [Sequenced Animations](https://github.com/jlmakes/scrollreveal.js#31-sequenced-animations).

**Comment by snoopy15** [comment]
Thank you for answer.

I tried with Sequence Animations:

```
window.sr = ScrollReveal({ duration: 2000 });
sr.reveal('.grid-items .item', 50);
```

but I have same issue. Items are appearing all together, not separately. 

Please take a look at link I sent you.

**Comment by jlmakes** [comment]
Are you calling `sr.reveal()` after the page has completed loading? Images by default with 0 height before they've loaded, so it's possible the elements are technically visible when `sr.reveal()` is called because the images haven't finished loading.

Just a theory, but I would verify that `sr.reveal()` is being called last. If you're using a progress bar library, there's likely a callback you can use.

**Comment by snoopy15** [comment]
I tried to put it in footer to be sure, but same happened. Also I tries to use JS to load it after whole page loaded using this window.onload = function(){} but same happens.

Can't figure out what's the problem

**Comment by jlmakes** [comment]
Putting scripts in the footer or `window.onload` could still trigger before your progress bar and content is finished loaded. What library are you using to show the progress?

Have you tried a really long duration to confirm the library is revealing properly, even if the timing is wrong?

**Comment by tysonyau** [comment]
I was trying to replicate the same effect. If you look closely at the source, a sequence class was applied to the first element of each row. Sequence animations are fired on load and not scroll. To stagger the animation on scroll, you will need to do the following.

```
var srIndex = 0,
      srLastPos = 0,
      srCurrentPos;

    var srConfig = {
        beforeReveal: function (domEl) {
            srCurrentPos = domEl.offsetTop;

            if(srLastPos == srCurrentPos) {
                srIndex++;
            } else {
                srIndex = 0;
            }

            srLastPos = srCurrentPos;
            domEl.className += ' delay-' + srIndex;
        }
    };

    window.sr = ScrollReveal(srConfig);
```

Before the reveal is triggered, I increment a delay class if multiple elements have the same top position. You can easily add the delay with incline css or classes applied in your stylesheet.

Hope that helps!

**Comment by jlmakes** [comment]
>Sequence animations are fired on load and not scroll.

This isn't quite right. Sequences are triggered whenever _any_ element in the set is visible.

**Comment by snoopy15** [comment]
Hi guys, thank you for your answers.

@tysonyau I tried your solution, but it's same. It didn't helped. I have few elements that should be reload on load and then others should load on scroll.

**Comment by jlmakes** [comment]
@snoopy15 Like @tysonyau points out, I am using the [Sequencer](https://github.com/jlmakes/scrollreveal#31-sequenced-animations) to reveal elements for the first row of the demo. This is why they reveal one after another.

**Comment by VidyChan** [comment]
Sorry for reopening this old issue but none of the methods mentioned works. I ended up going through the code at https://scrollrevealjs.org/ and found out that you need to add `interval: 220` 
(or your value) to the options

```javascript
ScrollReveal().reveal(".reveal", {
	// other options
	interval: 220,
	// other options
});
```
