### ISSUE TITLE
Uncaught TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by sutris-sdp** [jlmakes/scrollreveal#303]
Currently, I'm developing a website which can be accessed via http://inside-prot.surge.sh/. Sometimes, I get this error `Uncaught TypeError: Cannot read property 'config' of undefined` when opening the url above. It happens randomly and I'm not sure the exact way to reproduce it. If you are unable to get the error when opening the url above, try refresh the page a few times (usually around 5-10 times works).

More details about me:
- My operating system is OS X 10.11.6 
- I'm using Google Chrome 53.0.2785.143 (64-bit)
- I'm using ScrollReveal v3.2.0
- For details about how I use ScrollReveal, please take a look at the [following code](https://github.com/inside-interior/inside-web/blob/master/src/js/home.js#L79-L101) 

Thanks! 😄

**Comment by jlmakes** [comment]
Sounds like a race condition somewhere.

Can you temporarily use unminified files on your website? I can't trace the error.

**Comment by sutris-sdp** [comment]
Sorry, I gave the minified version. Now, it should use unminified files :)

**Comment by jlmakes** [comment]
Looks like something to do with asynchronously loaded and/or cached content.

I'm not sure how exactly you're running your scripts, but the `ScrollReveal` constructor and your `scroll_reveal` instance are not accessible in the console for me. It's helpful when these are available globally for debugging.

Never the less, the problem is because your HTML has `data-sr-id` attributes (and even the initial styles) -- so when you attempt `scroll_reveal.reveal()`, it finds the existing id and looks for that entry in the data store; it of course can't find it because this is a fresh page load.

Hopefully that helps point you in the right direction.

**Comment by jlmakes** [comment]
Only having the issue in production also suggests some type of caching issue to me.

Soon I will add a new method to clean the DOM of `data-sr-id` attributes, inline styles and event listeners. (Feature request #227.) There's enough asynchronous websites and single-page applications that can benefit from hitting the "reset button".

**Comment by sutris-sdp** [comment]
Hi, @jlmakes.

Turns out the issue is because I initialize `ScrollReveal` object twice (i.e. calling) to the same variable and call `reveal()` function twice. Thank you very much for kindly helping even though it was my fault.

**Comment by jlmakes** [comment]
Thanks for the update! Glad you figured it out.

**Comment by su-narthur** [comment]
@jlmakes "P.S. Soon I will add a new method to clean the DOM of data-sr-id attributes, inline styles and event listeners. (Feature request #227.)"

Did this ever git added?

**Comment by su-narthur** [comment]
Here's a jQuery solution that worked for me:

```
jQuery('[data-sr-id]').removeAttr('data-sr-id').removeAttr('style');
```

**Comment by jlmakes** [comment]
Nice @su-narthur, that’s a straight forward way to "uninitialize" ScrollReveal elements.

I'd like to add however, that your solution doesn’t unbind any event listeners, and unconditionally destroys the style tag—which may contain styles not generated by ScrollReveal.

Good news though, #227 made it's way into [Version 4](https://github.com/jlmakes/scrollreveal/pull/323), which you can help beta test today!

The new documentation will be online in the next few weeks, but the `sr.destroy()` method has been added to the v4 API. It’s also worth mentioning that in the next beta release, I plan to expand to `destroy(arg)` so an optional parameter (selector, Node or NodeList) can limit the scope of cleanup.
