### ISSUE TITLE
Using ScrollReveal in Node?

### ISSUE THREAD

**Issue by siamak** [jlmakes/scrollreveal#304]
I'm using ScrollReveal in an isomorphic app (React + Webpack). I get this error when I build:
```
node_modules/scrollreveal/dist/scrollreveal.js:96
ReferenceError: window is not defined
```

**Comment by jlmakes** [comment]
This is not specific to ScrollReveal. The `window` object is not available in node, only the browser.

I'm not experienced with Isomorphic app development, but for code that requires `window`, the only proposed solution I found (that made sense) is to inject it with `<script>` tags into your templates.
