### ISSUE TITLE
[Q] Using different option per element

### ISSUE THREAD

**Issue by dehghani-mehdi** [jlmakes/scrollreveal#306]
Hi,

Thanks for your amazing plugin. as you removed `data attribute` support, I wonder how I can use different config, based on `end-user` setting. I mean, imagine I have a config page that has demonstration of some different animations that user can select one of them.
Is there any built-in way that can pass config to `scrollreveal`?
```html
<div data-config="{duration: 2000}"></div>
<div data-config="{duration: 1000}"></div>
```

Should I loop through the `div` element and pass the config by reading the `data attribute` value? or there is another/better way?

Thanks !

**Comment by dehghani-mehdi** [comment]
No, I'm not.

Yes, if I do something like this, it will work:

    window.sr = ScrollReveal();
    var divs = document.querySelectorAll('div');
    for(var i = 0; i < divs.length; i++)
    {
        sr.reveal(divs[i], JSON.parse(divs[i].dataset.config));
    }

I asked the question, because I want to know if there is another/better/built-in way to do that.

And the `data-config` comes with `HTML` from server, in my project, admin can select the animation from the provided list (I have something like [this](http://jackonthe.net/css3animateit/examples/) page).

**Comment by jlmakes** [comment]
What do you think about just appending a class name?
- Administrator selects `fadeInUp`
- Server sends `<div class="fadeInUp"></div>`
- Your client JavaScript then looks like this:
```js
window.sr = new ScrollReveal();

var fadeInUp = {
  origin: bottom,
  distance: '50px'
}

sr.reveal('.fadeInUp', fadeInUp);
```

**Comment by dehghani-mehdi** [comment]
That's way I asked this question, looks like better than my solution. thanks man. I close the issue, if there was something wrong with the idea, I'll keep you posted.

Big thanks for reply too fast to issues, btw.

**Comment by bjmiller121** [comment]
For future travelers, data attributes can be added very simply like this (using jQuery in this example, but could easily be vanilla JS):

``` js
// Grab all elements to scroll reveal
var $scrollElement = $('.scroll-reveal');

// Initiate scroll reveal
window.sr = ScrollReveal();

// For each scroll reveal element, set the data attributes as the options
$.each($scrollElement, function() {
  sr.reveal(this, $(this).data());
});
```

Then your markup can look like this:

``` html
<div class="scroll-reveal" data-delay="500" data-scale="0.5" data-{option}="{value}">
  Content
</div>
```

**Comment by ugrupp** [comment]
Yup, unfortunately this doesn't seem to work with using `interval`.
