### ISSUE TITLE
scrollreveal.js distribution file broken?

### ISSUE THREAD

**Issue by David-van-den-Bor** [jlmakes/scrollreveal#309]
Scrollreveal `v3.3.2` seems to be buggy somehow. Is it missing something?

v3.1.3` is working just fine in my project, but if upgrade to `v3.3.2`, animations no longer work.

And this is how I initiate scrollreveal.js

```javascript
window.sr = ScrollReveal ({
  // Animation defaults
  origin      : 'bottom',
  distance    : '30px',
  duration    : 500,
  delay       : 0,
  rotate      : { x: 0, y: 0, z: 0 },
  opacity     : 0,
  scale       : 1,
  easing      : 'cubic-bezier( 0, 0, 0, .9 )',
  // Options defaults
  container   : null,
  mobile      : true,
  reset       : true,
  useDelay    : 'always', // always | once | onload
  viewFactor  : 0.20,
  viewOffset  : { top: 0, right: 0, bottom: 0, left: 0 },
  afterReveal : function( domEl ) {},
  afterReset  : function( domEl ) {}
});

var fadeIn = {
  delay:400,
  duration    : 500,
  distance    : '20px',
  easing:'ease-out',
  reset:true
};


window.sr = ScrollReveal();
  sr.reveal( '.fa', { origin: 'right', duration:5000, distance:'50px' } )
  //.reveal( '.row', fadeIn )
  ;
});
```

**Comment by jlmakes** [comment]
Actually, `v3.3.2` fixes a bug with `config.container` where the default value wasn't correctly being assigned. In your instance, it has exposed an invalid configuration...

**You cannot use `config.container = null`**.

To see for yourself, you can roll back to `v3.1.3` and you'll notice that your `sr.defaults.container` is actually the `document.documentElement` not `null`. That is why your animations work, and why after you upgrade, they do not.

_Also..._

You're instantiating ScrollReveal twice in the example code your provided. I would suggest instead:

```js
var defaults = {
  // Animation defaults
  origin      : 'bottom',
  distance    : '30px',
  duration    : 500,
  delay       : 0,
  rotate      : { x: 0, y: 0, z: 0 },
  opacity     : 0,
  scale       : 1,
  easing      : 'cubic-bezier( 0, 0, 0, .9 )',
  // Options defaults
  container   : window.document.documentElement, // <html>
  mobile      : true,
  reset       : true,
  useDelay    : 'always', // always | once | onload
  viewFactor  : 0.20,
  viewOffset  : { top: 0, right: 0, bottom: 0, left: 0 },
  afterReveal : function( domEl ) {},
  afterReset  : function( domEl ) {}
};

var fadeIn = {
  delay       : 400,
  duration    : 500,
  distance    : '20px',
  easing      : 'ease-out',
  reset       : true
};


window.sr = new ScrollReveal (defaults);

sr.reveal('.fa', { origin: 'right', duration: 5000, distance: '50px' });
sr.reveal('.row', fadeIn);
```

**Comment by David-van-den-Bor** [comment]
Hi Julian!

Thanks for the swift reply :-)
I reconfigured the INIT settings like you suggested and animations are working fine now. One small question: when the elements targeted for animation appear at the top of the page (on page load in full view), the animations aren't working (fade in from the right, for instance). They are only triggered when I scroll **down** te page, and **then** back up :-)

Kind regards and thanx in advance, David!
