### ISSUE TITLE
Scrollreveal not working with owl-carousel

### ISSUE THREAD

**Issue by mohammed-najeeb** [jlmakes/scrollreveal#310]
Before submitting a new issue, **please search existing issues.**

If you cannot find an existing discussion to join, please make sure to include the following with your new issue:

- What operating system you are using
- What browser (and version) you are using
- What ScrollReveal version you are using
- Detailed description of the problem
- Code sample demonstrating the problem (recommended)

Thanks!

**Comment by mohammed-najeeb** [comment]
only first slide is working

**Comment by jlmakes** [comment]
Using ScrollReveal with carousel plug-ins has come up a few times before.

Please search through [past issues](https://github.com/jlmakes/scrollreveal/issues).
