### ISSUE TITLE
Elements with overflow hidden not revealing

### ISSUE THREAD

**Issue by kirloi** [jlmakes/scrollreveal#315]
I'm new with scroll reveal but i've searched and i think nobody addressed this problem right or this is a new thing... Help me if I'm wrong.

I'm using sreveal in my upcoming site and I'm using the a similar method i've read in past issues (creating a container with a scroll bar) but it can't really work with it.

My setup is really basic:

```html
<body>
    <div class="target container" style="height:500px, overflow: scroll">
      <a class="sreveal">
      <a class="sreveal">
      <a class="sreveal">
```

The thing is, is not working... My first 3 `<a>`  are showing the rest are not but they are there. 

Proof (the gray area is a <a> with is visibility at 0, and the white bar is the horizontal scroll):
![image](https://cloud.githubusercontent.com/assets/10514968/20458922/854f93fc-aea9-11e6-8b28-3bb34036dab1.png)

**Comment by jlmakes** [comment]
And what does your JavaScript look like?

**Comment by kirloi** [comment]
It easier to explain if I send a pic, hope you don't mind. And im putting the "scrollreveal.min.js" before my main .js, if that helps in anyway
![image](https://cloud.githubusercontent.com/assets/10514968/20459663/bba3d2a2-aec1-11e6-80b1-97f60302c07f.png)

**Comment by jlmakes** [comment]
You're close @kirloi, you just need to add your container to your reveal.

```js
window.sr = ScrollReveal({ reset: false });

sr.reveal('.sreveal', {
  container: '.target.container',
  distance: '60px',
  duration: 1000,
  scale: 1,
});
```

**Comment by kirloi** [comment]
Yup, that's the thing. ;) **resolved**
