### ISSUE TITLE
viewFactor as a constant instead of percentage based

### ISSUE THREAD

**Issue by promptdev** [jlmakes/scrollreveal#316]
Perhaps this may be more of a feature request, not actually an issue...

Im using scrollReveal to show full width section blocks as users scrolls down the page, sections which can sometimes be rather large in height. The percentage based viewFactor then would require a substantial amount of scroll before the animation is triggered leaving the viewport empty for a while.

An approach to set viewFactor as a constant https://github.com/jlmakes/scrollreveal/pull/317

**Comment by promptdev** [comment]
https://github.com/jlmakes/scrollreveal/pull/317

**Comment by jlmakes** [comment]
`viewFactor` changes the boundaries of elements, using percentages.
`viewOffset` changes the boundaries of the container, using pixels.

Sounds like you're looking for the `viewOffset` option for this task.
Please play around with it to get a feel for it — check out this [JSbin](http://jsbin.com/zegoxawupi/edit?js,output)

_Example:_
```js
ScrollReveal({
  reset: true,
  viewOffset: { top: 100, bottom: 100 }
}).reveal('.box');
```

This will change the top boundary to 100px from the top, and the bottom boundary 100px from the bottom... effectively squishing the active container boundaries vertically.

This should give you the effect you're looking.

**Comment by promptdev** [comment]
Hi @jlmakes,
thank you for the input.

The reason why I thought on trying to come up with something is because I tried using `viewOffset` but was running into the same problem, I guess because I didn't set the `viewFactor` option to `0`.
Now I'm following your recommendations but now it seems I have a bigger problem which I'm still trying to figure out.

Strangely, when setting `viewFactor: 0, viewOffset: { top: 100, bottom: 100 }` no reveal is occurring on scroll, the plugin seems to be initialising because I see the styles being inserted into the items but the opacity never changes from 0 to 1 on scroll... haven't been able to replicate it to a jsbin, so perhaps there's something fishy happening with the rest of my code.

Will post back here if I find a solution to my problem, for the mean time if anything I said makes sense and you could throw some pointers, that'd be greatly appreciated.

Thanks!

**Comment by promptdev** [comment]
Some other findings, perhaps this will bring more clues... can't find what is causing this behaviour.
When setting the `viewFactor` to other value than `0` the reveal items inline CSS is as follows:

`; visibility: visible;  -webkit-transform: scale(1); opacity: 1;transform: scale(1); opacity: 1;-webkit-transition: -webkit-transform 0.7s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.7s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; transition: transform 0.7s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.7s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; `

but if set to `0` then they get:

`; visibility: visible;  -webkit-transform: scale(1); opacity: 0;transform: scale(1); opacity: 0;`

... missing the `transition` declarations.

**Comment by jlmakes** [comment]
I don't mind working through some examples, but I'll need you to put together a JSBin or something so we can look at and work on the same thing.

**Comment by promptdev** [comment]
Hi @jlmakes,
I've set a test page on my staging env, if you could have a look that'd be greatly appreciated!
The test page is : http://serpentine.prompt-dev.com/test/

I've set the scrollReveal options as follows:

```
window.sr = new ScrollReveal({
	distance: '20px',
	duration: 700,
	scale: 1
});

sr.reveal( $('.page-wrap > *'), {
	distance: 0,
	reset: true,
	viewFactor: 0,
	viewOffset: { top: 100, bottom: 100 }
});
```

In the rest of the pages of that staging link, you'll see that scrollReveal is working with no problems with the `viewFactor` set to default. Take for instance: http://serpentine.prompt-dev.com/lookbooks/serpentine-by-francesco-nazardo/

Thanks in advance!

**Comment by jlmakes** [comment]
@promptdev I've noticed a problem: you're using a jQuery object as your reveal target, which is not supported (and not necessary!)

```js
sr.reveal( $('.page-wrap > *'), {
	distance: 0,
	reset: true,
	viewFactor: 0,
	viewOffset: { top: 100, bottom: 100 }
});
```

Can simply be written:

```js
sr.reveal('.page-wrap > *', {
	distance: 0,
	reset: true,
	viewFactor: 0,
	viewOffset: { top: 100, bottom: 100 }
});
```

**Comment by promptdev** [comment]
Hey @jlmakes,
thank you mate for having a look! Can't argue, thats definitely more elegant! :P 
... but still is not fixing the issue :(

Just updated  http://serpentine.prompt-dev.com/test/ with your recommendations.
What I can see –even with the jQuery selector but now gone– is scrollReveal kicking in and all of the styling applied to the containers but the `opacity` animation never triggers on scroll, it remains at `0` no matter what.

Then again http://serpentine.prompt-dev.com/lookbooks/serpentine-by-francesco-nazardo/ works with `viewFactor` set as default.

Hope that makes sense.

**Comment by jlmakes** [comment]
Hmm, can you use unminified scripts on the test page so I can help debug?

**Comment by promptdev** [comment]
Really appreciate!
http://serpentine.prompt-dev.com/app/wp-content/themes/serpentinemx/dist/scripts/main.js
...line 15921

Im using quite a few plugins, though I have tested without most of them. Then again what I don't get is that it does work if `viewFactor` is set to default. 
```
├── animate.css#3.5.2
├── animsition#4.0.2
├─┬ bootstrap#4.0.0-alpha.4 (latest is 4.0.0-alpha.5)
│ ├── jquery#3.1.0 (3.1.1 available)
│ └── tether#1.3.7 (1.3.8 available)
├── css-hamburgers#0.5.0 (latest is 0.6.0)
├── enquire#2.1.2
├─┬ flickity#2.0.4 (2.0.5 available)
│ ├── desandro-matches-selector#2.0.1
│ ├── ev-emitter#1.0.3
│ ├─┬ fizzy-ui-utils#2.0.3
│ │ └── desandro-matches-selector#2.0.1
│ ├── get-size#2.0.2
│ ├─┬ tap-listener#2.0.0
│ │ └─┬ unipointer#2.1.0
│ │   └── ev-emitter#1.0.3
│ └─┬ unidragger#2.1.0
│   └── unipointer#2.1.0
├─┬ flickity-bg-lazyload#1.0.0
│ ├── fizzy-ui-utils#2.0.3
│ └── flickity#2.0.4 (2.0.5 available)
├── font-awesome#4.6.3 (4.7.0 available)
├─┬ imagesloaded#4.1.1
│ └── ev-emitter#1.0.3
├─┬ masonry#4.1.1
│ ├── get-size#2.0.2
│ └─┬ outlayer#2.1.0
│   ├── ev-emitter#1.0.3
│   ├── fizzy-ui-utils#2.0.3
│   └── get-size#2.0.2
├── picturefill#3.0.2
└── scrollreveal#3.3.2
```

**Comment by jlmakes** [comment]
There's no way I can go through 16,000 lines of JavaScript.

You can inspect the `sr` object and see that all the elements are correctly configured, and have the initial transform styles. However, they are never considered visible and thus transition and target transform styles are never applied.

I've provided a working (and isolated) example of `viewFactor: 0` working correctly, and if you look at the source below... you can see it's aliased as the variable `vF` only used in a few places to change the boundaries of elements.

I'm not sure what else I can you troubleshoot.

<details>
<summary>Source</summary>

```js
function _isElemVisible (elem) {
  var offset = _getOffset(elem.domEl)
  var container = _getContainer(elem.config.container)
  var scrolled = _getScrolled(elem.config.container)
  var vF = elem.config.viewFactor

    // Define the element geometry.
  var elemHeight = offset.height
  var elemWidth = offset.width
  var elemTop = offset.top
  var elemLeft = offset.left
  var elemBottom = elemTop + elemHeight
  var elemRight = elemLeft + elemWidth

  return confirmBounds() || isPositionFixed()

  function confirmBounds () {
    // Define the element’s functional boundaries using its view factor.
    var top = elemTop + elemHeight * vF
    var left = elemLeft + elemWidth * vF
    var bottom = elemBottom - elemHeight * vF
    var right = elemRight - elemWidth * vF

    // Define the container functional boundaries using its view offset.
    var viewTop = scrolled.y + elem.config.viewOffset.top
    var viewLeft = scrolled.x + elem.config.viewOffset.left
    var viewBottom = scrolled.y - elem.config.viewOffset.bottom + container.height
    var viewRight = scrolled.x - elem.config.viewOffset.right + container.width

    return top < viewBottom &&
      bottom > viewTop &&
      left > viewLeft &&
      right < viewRight
  }

  function isPositionFixed () {
    return (window.getComputedStyle(elem.domEl).position === 'fixed')
  }
}
```

</details>

**Comment by jlmakes** [comment]
I can't think of why `viewFactor: 0` would be impacting element visibility in such a way that they would no longer be considered visible; by definition it means that only 1 pixel has to be in bounds for the element to be considered visible... it's the most lenient configuration.

A single 3rd party library maybe, but 16,000 lines of code is outside the scope of what I can offer support for. If you can put together an isolated demonstration of a problem, I will promptly work on patching ScrollReveal, but I have nothing else to suggest other than working the process of elimination.

**Comment by promptdev** [comment]
Thank you @jlmakes I really appreciate the help, I definitely understand and never assumed you were going to review all the way through 16,000+ lines of code. Just wanted to show you how its being implemented and specially that even with all of that stuff scrollReveal works fine when setting `viewFactor` to its default.

Will post here when finding the solution.
Cheers mate, have a good one!

**Comment by jlmakes** [comment]
@promptdev The last thing I can think of is, try experimenting with `viewFactor: 0.01` for example. It might be interesting to see if there's a point at which it starts to work...

It's not really tackling the root of the problem, but it might be a step forward.

**Comment by promptdev** [comment]
@jlmakes you were right! I went down from `viewFactor: 0.1` and it works until getting down to `viewFactor: 0.0000000000000001` when no reveal is occurring.
