### ISSUE TITLE
quirky behavior in mobile origin: 'right', distance:'500px'

### ISSUE THREAD

**Issue by Blastnsmash** [jlmakes/scrollreveal#318]
Hi @jlmakes

Here is a screencast demonstrating the problem:
https://drive.google.com/file/d/0B-M6Yes83t08ZnRRbld0czBJYnM/view?usp=sharing

- Windows 10
- Chrome 55.0.2883.87 (Mobile emulator)
- ScrollReveal 3.3.2

Thanks!

**Comment by jlmakes** [comment]
Hey @Blastnsmash, thanks for the details.

See [#50](https://github.com/jlmakes/scrollreveal/issues/50#issuecomment-60030918) for more information.

>"should you choose to use reveal animations that position your elements outside their container and/or body, you will have to find a way to deal with element overflow suited to your particular use case and DOM structure."

Are you using `overflow-x: hidden` on your containers for mobile?

**Comment by Blastnsmash** [comment]
That is the problem indeed.
Very helpful thank you.

We must be inheriting something in one of our frameworks that is removing the overflow:hidden when the device is considered mobile.

**Comment by MitHipster** [comment]
I read through all the overflow posts, but I am still having an issue on mobile and using `overflow-x: hidden` is not doing the trick. I am using Foundation as my framework. Do you know if this could be causing the issue? Also, is there a way to define one set of scroll reveals for mobile and another for desktop? Thanks.

**Comment by jlmakes** [comment]
@MitHipster I am not familiar with Foundation. Unless you can reproduce the issue with [JSBin](https://jsbin.com), there’s not much I can do. I recommend using remote debugging, to use your desktop browser’s inspector on your mobile site—it makes CSS things like this much simpler to solve.

For separate questions, next time please open a new issue. That way I can ensure the title and labels are helpful to others in the future searching for a similar solution.

> "Also, is there a way to define one set of scroll reveals for mobile and another set for desktop? Thanks."

The simplest way to do this is to use ScrollReveal v4 (currently in beta), which includes `options.mobile` and the new `options.desktop` to handle targeting device types.

_Example:_

```js
sr.reveal('.only-on-desktop', { mobile: false })
sr.reveal('.only-on-mobile', { desktop: false })
```

You can install it like this:
* `npm install scrollreveal@beta`
* or grabbing the script directly: https://unpkg.com/scrollreveal@4.0.0-beta.8

For information on what's new (or changed), please see the [change log](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md)

Good luck!

**Comment by MitHipster** [comment]
Thank you very much for the quick response and sorry for posing separate questions under one thread. I look forward to giving the beta try.

**Comment by jlmakes** [comment]
@MitHipster no worries, just trying to keep things organized ;)
