### ISSUE TITLE
on scroll after animation text showing bold 

### ISSUE THREAD

**Issue by kchabra093** [jlmakes/scrollreveal#320]
I am facing issue with text animation after completing animation text showing is bold.

**Comment by jlmakes** [comment]
Can you take a screenshot?

**Comment by kchabra093** [comment]
Now problem is solved, it's browser render issue. After reveal animation on elements add class. and set class property this -webkit-font-smoothing: subpixel-antialiased;

**Comment by jlmakes** [comment]
This may be related to #292 and how browsers render transformed elements: they can appear blurry. I'm working on a fix for this.

**Comment by kchabra093** [comment]
![actulal-font](https://cloud.githubusercontent.com/assets/22699830/21631462/761c8f6c-d261-11e6-8f3a-41169970135b.png)
![font-bold-render](https://cloud.githubusercontent.com/assets/22699830/21631465/7a7daaaa-d261-11e6-8082-db75f4328dbe.png)

**Comment by kchabra093** [comment]
After revealing animation  added class on animated content "subpixel"

.subpixel{ animation: font-weight .0000001s;}
@keyframes font-weight {
    0%{}
    100%{ -webkit-font-smoothing: antialiased; }
}

**Comment by jlmakes** [comment]
If you remove the `style` attribute from the elements (removing the styles ScrollReveal adds to the elements), does the bold appearance go away?

**Comment by kchabra093** [comment]
If I remove ScrollReveal adds from elements or uncheck - check font-weight from inspect element. font weight back bold to normal.
