### ISSUE TITLE
Example how to set up with Vue?

### ISSUE THREAD

**Issue by nucamoz** [jlmakes/scrollreveal#326]
Hello. Thanks for great library. I am new to Vue, so it's pretty hard for me to figure out how to set up simple animation with Vue and ScrollReveal. 

Can someone please show me how to do that or at least give me some tips? Thank you.

**Comment by jlmakes** [comment]
Hey @nucamoz,

Check out the [instance lifecycle](https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks) and the [`v-cloak` directive](https://vuejs.org/v2/api/#v-cloak) in the Vue documentation.

Afterwards, this example should make sense: https://jsfiddle.net/sx1xhkgm/

There are surely other ways to get this done, but this should point you in the right direction.
