### ISSUE TITLE
Possible to do a scale up then down in the same transition?

### ISSUE THREAD

**Issue by CrashyBang** [jlmakes/scrollreveal#327]
- What operating system you are using
Ubuntu: 16.04
- What browser (and version) you are using
Chrome 55
- What ScrollReveal version you are using
3.3.2
- Detailed description of the problem
I would like to fade in and ease to a scale of 1.1 then ease back down to a scale of 1 is this possible in one transition?
- Code sample demonstrating the problem (recommended)
Have tried:
```js
settings: {
    duration: 2000,
    easing: 'ease-in-out',
    scale: 1.1
}, delay: 250
```
But this only scales down from `1.1`

Thanks!

**Comment by CrashyBang** [comment]
Never mind got it was didn't really understand the `easing` key got it now :) Really good resource [here](http://easings.net/) if anyone stumbles across this issue :).

**Comment by jlmakes** [comment]
Glad you got it working @CrashyBang

Also, something like http://cubic-bezier.com/ is great for creating custom easing to drop into ScrollReveal.
