### ISSUE TITLE
Slide in effect?

### ISSUE THREAD

**Issue by CrashyBang** [jlmakes/scrollreveal#328]
I would like to slide an element in from essentially off screen left. Tried the `origin` option but that is still relative to where the element is declared.

Is something like this possible or are all animations relative to where the element is in the markup?

Thanks!

**Comment by jlmakes** [comment]
Hi @CrashyBang,

The element's final position is determined by your markup and style; the configuration you pass to ScrollReveal describes the animation's starting position.

If you would like an element to enter from off screen, you need to provide at least `origin` and `distance` options. I would also recommend adding `overflow-x: hidden` to your page or animation container, to prevent scrollbars during animation (and remove [unwanted space on mobile devices](https://github.com/jlmakes/scrollreveal/issues/50#issuecomment-60030918)).

_Basic Example:_
```js
sr.reveal('#example', {
	origin: 'left',
	distance: '100%',
});
```

Keep in mind that `100%`here refers to 100% of the element width, not container width. In this **[working demo on JSBin](http://jsbin.com/cuyaqa/edit?html,css,js,output)**, the element is essentially a full screen width... so by animating it's width, it effectively comes from off screen.

If you want to move an element from off screen that is not a full screen width, it's up to you to determine the appropriate value for the `distance` option... perhaps by calculating the distance between the element and the left boundary, and adding the elements width to that value.

Hope this helps!

**Comment by CrashyBang** [comment]
Hey @jlmakes awesome that is exactly what I needed to get started :) thank you!
