### ISSUE TITLE
Staggering animations on load

### ISSUE THREAD

**Issue by grahammcuk** [jlmakes/scrollreveal#330]
I'm trying to create a very simple reveal when a grid of items enter the viewport. However, I also want to have a slight delay on each when the page loads

Here is a very crude codepen: http://codepen.io/grahammcuk/pen/xqZVRM

You can see that when a delay is applied, the scroll reveals no longer work. In a previous issue ( #299 ) you state "_any visible element in the set will trigger the sequence. So if some part of the sequence is visible on load, then you can trust the entire set will reveal_".

In my example above, items are visible on payload, so the sequence is triggered and all of the items animate in, but is there a way to also have them animate in/out when they enter/leave the viewport?

Thanks in advance!

**Comment by jlmakes** [comment]
What you have described has been requested many times @grahammcuk, but it's not possible with version 3.

Luckily, this is one of the major feature improvements of version 4, which is in public beta: https://github.com/jlmakes/scrollreveal/pull/323

It's stable in all tests thus far, and is 99% backwards compatible. Please see the [change log](https://github.com/jlmakes/scrollreveal/blob/v4.0.0-beta.1/CHANGELOG.md) for more information, but you will likely be able to simply drop this into your project and have your sequences behave as you've described.

Your feedback on the beta would be greatly appreciated. A brand new website and documentation is coming soon as well, so your ongoing participating is welcome.

**Comment by grahammcuk** [comment]
Sounds great @jlmakes :)

Would the javascript in my codepen achieve the effect I'm after?

Thanks

**Comment by jlmakes** [comment]
I believe so.

Drop in the version 4 beta with this:
```
https://unpkg.com/scrollreveal@4.0.0-beta.1/dist/scrollreveal.min.js
```

**Comment by grahammcuk** [comment]
Great! I'll let you know how I get on...
