### ISSUE TITLE
Grab element that was scrollrevealed in callback

### ISSUE THREAD

**Issue by rplumlee** [jlmakes/scrollreveal#331]
I have a situation where I have several elements of the same class that have scroll reveal applied to them. They each need a subsequent delayed fadein of a content section within the element.

My thought is to use the `afterReveal` callback, but I can't figure out how to grab the specific instance of the original element to find the element inside of it.  Here is the code of what I want to happen:

```js
delay: 100,
    afterReveal: function(){
		setTimeout(function(){
			$(this).find('.featured-content').css('opacity', '1')
		}, 500);
    }
});
```

The problem being, `$(this)` doesn't refer to the element being revealed, it appears to refer to a scroll reveal object, which doesn't seem to have the target element as a property.

Is there any way for me to call the specific instance of the original element being revealed in the callback?

**Comment by jlmakes** [comment]
Each callback function is passed the DOM node as the only function argument.

```html
<div id="example">Hello</div>
```
```js
sr.reveal('#example', {
	afterReveal: function (el) {
		// Inside the callback `el` --> #example
	}
)
```

**Comment by rplumlee** [comment]
Wonderful - I probably should have realized that. Thank you for the prompt response.
