### ISSUE TITLE
Reset only when scrolling UP

### ISSUE THREAD

**Issue by dadodado79** [jlmakes/scrollreveal#332]
Hi everybody,
there is a similar issue on this link

https://github.com/jlmakes/scrollreveal/issues/179
 
but it's never been solved and probably it's referring to a previous version of the script so I'm creating a new one. Is there a way to enable the reset function only when the page is scrolling up?
Thanks

**Comment by jlmakes** [comment]
@dadodado79 So you want reveal animations to play each time you scroll down, but not when you scroll up?
