### ISSUE TITLE
Sequenced Animations for all items

### ISSUE THREAD

**Issue by AbrahamHalil** [jlmakes/scrollreveal#339]
Hi,

I try to make "Sequenced Animations". If i add the code below, only the first items are waiting for the scrolling, all the others are already visible before scrolling.

Thanks for any Helps

```js
// interval passed to reveal
window.sr = ScrollReveal({ duration: 2000 });
sr.reveal('.box', 50);

// or...

// interval and custom config passed to reveal
window.sr = ScrollReveal();
sr.reveal('.box', { duration: 2000 }, 50);
```

**Comment by jlmakes** [comment]
You’ve done nothing wrong @AbrahamHalil.

This has come up a few times before #305 #297 #272. In short, this is a known limitation of the sequencer. The good news is that one of the biggest improvements I’ve made to the new [version 4](https://github.com/jlmakes/scrollreveal/pull/323) is the new sequencer.

If you’d like, check out [what's different in v4](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md) and give the beta a try:
```
https://unpkg.com/scrollreveal@4.0.0-beta.3/dist/scrollreveal.min.js
```
It’s already quite stable (and in use on scrollrevealjs.org), but your feedback would be greatly appreciated—just post your thoughts, experiences, bugs, etc. [here](https://github.com/jlmakes/scrollreveal/pull/323).

**Comment by AbrahamHalil** [comment]
perfect, it works, thank you
