### ISSUE TITLE
Can't get the set up correctly

### ISSUE THREAD

**Issue by dangus21** [jlmakes/scrollreveal#340]
I'm trying to use the plug in, but no matter what i cant get it to work…

Here is the pen i'm trying to work it in:
http://codepen.io/angus/pen/rmLXEK?editors=0110

i want the .toShow element to show when i scroll to it … and if possible, give it possition fixed

**Comment by jlmakes** [comment]
The `div.toShow` is just a transparent box, with no content; it is working, there's just no visual elements for you to notice. Try adding content, or a background color.

**Comment by dangus21** [comment]
after it is shown, is there a way to set it fixed at a certain position?

**Comment by jlmakes** [comment]
There is an `afterReveal` callback available, which can be used like this:

```js
sr.reveal('.toShow', {
    afterReveal: function (el) {
        // do something with el...
    }
});
```
