### ISSUE TITLE
Reveal Sequencer only on visible elements?

### ISSUE THREAD

**Issue by ekfuhrmann** [jlmakes/scrollreveal#342]
I saw in your notes for the beta, the following:
> Elements in a reveal sequence are no longer grouped, and reveal progressively when visible

However, when I uploaded the beta code, the sequencer was working the same as before where it would just hit all elements in the sequence on the page once the first initialized the sequence, regardless of whether the others were in view or not.

Here is the code I'm using for the sequencer:
```js
sr.reveal('.sr-stagger-bottom', {
    duration   : 700,
    distance   : '30%',
    easing     : 'ease-in-out',
    origin     : 'bottom',
    scale      : 0,
    viewFactor : 0.5,
  }, 200);
```

Am I missing something more?

**Comment by jlmakes** [comment]
Check out this [sequencer demo](http://jsbin.com/kajohaf/1/edit?html,console,output) using the v4 beta.

You should be able to confirm you are using the v4 beta by examining the return value of `sr.value`.
(Keep in mind that the 4.0.0-beta.3 incorrectly returns `4.0.0-beta.2`, but that's a separate issue.)

**Comment by ekfuhrmann** [comment]
When I input `sr.version` I get back `"4.0.0-beta.0"`. That is even after copying over the code from [here](https://unpkg.com/scrollreveal@4.0.0-beta.3/dist/scrollreveal.min.js).

With that JS though, I did get the sequencer to work as expected; however now it is disregarding any origin attribute I give to it, so it is strictly just revealing the elements rather than transforming them too. Could this be a result of the version?
