### ISSUE TITLE
Delaying all animations on page load

### ISSUE THREAD

**Issue by grahammcuk** [jlmakes/scrollreveal#344]
Hi, 

I have a set ScrollReveal animations for various elements on a variety of different pages.

However, I have a short animation on page load and would like the ScrollReveal animations to start after this.

I tried wrapping the ScrollReveal javascript in a setTimeout which half worked, but the elements are all visible during the delay, then disappear, then animate in as usual.

Is there any way to delay all ScrollReveal animations by a few seconds?

Thanks

ps. I am using the ScrollReveal v4 beta, if that helps...

**Comment by jlmakes** [comment]
You can use `options.delay` to delay animations.

You can customize _when_ delays are used with `options.useDelay`, which has 3 possible values:
- `'always'` — delay every reveal animation
- `'once'`  — delay only the first time reveals occur
- `'onload'` — delay only for animations triggered by first load

_Example:_

```js
// two seconds of delay, only for reveals triggered on page load
sr.reveal('.mySelector', { delay: 2000, useDelay: 'onload' })
```

I’ll leave it up to you to experiment with these options to find the right effect.

Also, thanks for helping test the beta—I'm still working on the new website/documentation, but the current [readme/documentation](https://github.com/jlmakes/scrollreveal/blob/v3.3.5/README.md) is still relevant (after all, I'm doing my best to not break anything).

**Comment by grahammcuk** [comment]
Thanks for the help, the following code seems to have worked...

```
setTimeout( function(){

    sr.reveal('h3', { origin: 'bottom', distance: '50px', duration: 750, opacity: 0 }, 500);
    sr.reveal('.right', { origin: 'bottom', distance: '50px', duration: 750, delay: 300, opacity: 0 }, 500);

}, 1000); // delay on page load
```

You can see that I already delay the `.right` elements, so that approach wouldn't work. I added `visibility: hidden` to the elements and the `setTimeout` which hides the content until the javascript kicks in to reveal it. You're right though, this isn't very accessible for people on older browsers.

The v4 beta is great, thanks for sharing. The only issue I'm having is the common one when you scroll too fast and the animations aren't triggers. Any indication on when it'll be ready for release?

**Comment by jlmakes** [comment]
>The v4 beta is great, thanks for sharing. The only issue I'm having is the common one when you scroll too fast and the animations aren't triggers. Any indication on when it'll be ready for release?

I'm very close! The next release `v4.0.0-beta.4` will have that bug fixed, and should be out today or tomorrow. (Fingers crossed!)

**Comment by grahammcuk** [comment]
Awesome, please keep me updated :)
