### ISSUE TITLE
Restart animation when an element reach a starting point.

### ISSUE THREAD

**Issue by vmulot** [jlmakes/scrollreveal#347]
First of all, thanks for this plugin, it's really awesome :)

I need to use it with the `options.reset = false` so items won't vanish when they come out of viewport, but I need also to trigger this animation later.

I’ll try to explain:

First time page load, ScrollReveal occurs, then going on scrolling to bottom, etc etc, and then I go back to top. I need when scrolling from top, to restart ScrollReveal animation, but I don't wan't items to disappear.

Is there a way to "restart" the reveal? (when at top, the ScrollReveal is on next section)

I tried with waypoint.js to call `sr.reveal(myOptions)` again but it didn't work.

Thanks

**Comment by jlmakes** [comment]
There is a new `clean()` method in ScrollReveal version 4 that I think will work for your situation:

> `sr.clean(target)` removes ScrollReveal from the target element(s). This removes the generated styles and event listeners, which would set you up to reveal the elements again if you so choose.

_Step 1: (On page load)_ 

```js
const myOptions = {
	reset: false,
	easing: 'ease-in'
};

sr.reveal('.myElements', myOptions);
```

_Step 2: (In some callback when you reach the top of the page...)_
```js
sr.clean('.myElements');
sr.reveal('.myElements', myOptions);
```

This should successfully re-initialize your reveals.

**Comment by vmulot** [comment]
Thanks for help ! i tried and it worked ! but even if it's working i still having some js errors in console : 
`Uncaught TypeError: Cannot read property 'bounds' of undefined
    at ScrollReveal.isElementVisible (scrollreveal.js:172)
    at ScrollReveal.animate (scrollreveal.js:1029)
    at scrollreveal.js:1218
    at each (scrollreveal.js:80)
    at scrollreveal.js:1218
isElementVisible @ scrollreveal.js:172
animate @ scrollreveal.js:1029
(anonymous) @ scrollreveal.js:1218
each @ scrollreveal.js:80
(anonymous) @ scrollreveal.js:1218
`
and this message : ScrollReveal: Querying the selector "[data-sr-id]" returned nothing.

i'm not using the data-sr-* on my elements, should i ?

**Comment by jlmakes** [comment]
`data-sr-id` is the attribute ScrollReveal uses to track elements.

So the log output: `ScrollReveal: Querying the selector "[data-sr-id]" returned nothing.` is actually normal behavior right now... because ScrollReveal looks for that, but the `clean()` call removed them.

I plan on removing that log message, but that behavior is normal in this case.

**The error you’ve brought up however is news to me, and I will look into it.**
