### ISSUE TITLE
SRv4-beta.7 — options.scale = 0 only works in Safari

### ISSUE THREAD

**Issue by jlmakes** [jlmakes/scrollreveal#350]
Using `options.scale = 0` appears only to work on Safari. [JSBin Demo](http://jsbin.com/vijujujubi/edit?html,output)
For Chrome and Firefox, `options.scale` must be greater then `0`. [JSBin Demo](http://jsbin.com/bevuxuqiwi/edit?html,output)

_Bug submitted by @AbrahamHalil_

**Comment by jlmakes** [comment]
All the CSS transforms are generated using [Rematrix](https://github.com/jlmakes/rematrix), and I’ve [confirmed](https://jsfiddle.net/4Lymdc55/) the issue is not there.

**Comment by jlmakes** [comment]
This has been patched as of ScrollReveal v4.0.0-beta.8

**Comment by AbrahamHalil** [comment]
I think i am using "SRv4-beta.7". Did you released "v4.0.0-beta.8"?

**Comment by jlmakes** [comment]
Yep, just built and tested it.
https://unpkg.com/scrollreveal@4.0.0-beta.8
