### ISSUE TITLE
Suggestion: add debug flag to show/hide the console.log calls

### ISSUE THREAD

**Issue by toddholmberg** [jlmakes/scrollreveal#351]
Is it possible to add a debug flag to the configuration options that will show/hide the console.log() calls on the following lines? 

- 57
- 172
- 271
- 288
- 288

Thanks!

**Comment by jlmakes** [comment]
Great idea. This feature will make its way into the next beta release of ScrollReveal 4.

(v4.0.0-beta.9 will be out in the next few days.)
