### ISSUE TITLE
question about velocity.js

### ISSUE THREAD

**Issue by soniapello** [jlmakes/scrollreveal#353]
Hi It's not an issue just a question. ScrollMagic support [velocity animation](http://scrollmagic.io/examples/basic/simple_velocity.html) but it doesn't work with chaining animation like
```js
var scene = new ScrollMagic.Controller();

new ScrollMagic
    .Scene({ triggerElement: "#trigger", triggerHook: 'onLeave' })
    .setVelocity(".Imagem", { opacity: 0 }, { duration: 600 })
    .addTo(scene);
```
works but the next one doesn't
```js
var scene = new ScrollMagic.Controller();

new ScrollMagic
    .Scene({ triggerElement: "#trigger", triggerHook: 'onLeave' })
    .setVelocity(".Imagem", { scaleX: [1, 0] }, { duration: 600 })
    .setVelocity(".Ima", { opacity: 1 }, { duration: 600 })
    .addTo(scene);
```
I wonder if it can be done with ScrollReveal.
Thanks

**Comment by jlmakes** [comment]
Hi @soniapello,

I’m only vaguely familiar with both ScrollMagic and Velocity, so I’m not sure how much I can really offer here. What I can do, is emphasize what ScrollReveal is good at:

* Detecting when elements are visible within the viewport (or a custom container)
* Generating customizable CSS transitions
* Adding/removing that CSS based on element visibility

ScrollReveal does provide callback functions, so you can easily execute custom JavaScript when elements enter/leave the viewport if needed.

I’m not sure what you’re trying to achieve within your project, but _it looks_ like you’re trying to use ScrollMagic to detect visibility—and then use Velocity.js to trigger animations. If this is accurate, then it’s possible ScrollReveal could significantly streamline all of this for you.

**Comment by soniapello** [comment]
@jlmakes Thanks for your answer. I 'll try to make it work with the callback function when the new version of ScrollReveal comes out
