### ISSUE TITLE
Custom Scrollbar and SmoothScroll

### ISSUE THREAD

**Issue by grahammcuk** [jlmakes/scrollreveal#357]
Me again... :)

I'm trying to implement SRv4 together with a custom scrollbar/smoothscroll. 

The way it works is by adding *data-scrollbar* to the element you want to scroll, then it moves the div via `transform: translate3d` rather than the usual.

Is there any way to use your plugin together with this? I'm sure i've seen examples of them working together somewhere.

My codepen account is playing up, but I've put a quick demo of the scrollbar together here: http://www.grahammdonnell.co.uk/scroll.zip

Thanks in advance!

**Comment by grahammcuk** [comment]
ps. Here is the smoothscroll script I am using: https://idiotwu.github.io/smooth-scrollbar/

**Comment by jlmakes** [comment]
Hey @grahammcuk,

ScrollReveal uses `requestAnimationFrame` combined with native `scroll` events. According to the Smooth Scrollbar documentation, it uses `translate3d` to mimic scrolling—so there are no native scroll events being triggered.

Version 4 of ScrollReveal exposes the event handler as `sr.delegate`. With that in mind, take a look at this section of the Smooth Scrollbar docs:

> Since scrollbars will not fire a native scroll event, we need to registers thought scrollbar.addListener() method.
>
> Notice: the callback functions will be invoked in every small scrolling, so be careful not to add time-consuming listeners that will slow down scrolling.
>
> — [scrollbar.addListener()](https://github.com/idiotWu/smooth-scrollbar#scrollbaraddlistener)

The main difference is that the Smooth Scrollbar listener is a `function (status)` (see the docs for the status object definition) and `sr.delegate` is a `function (event)`—so you can’t pass it directly.

If I were in your situation, I would start by trying to connect the two libraries like this:

```js
/**
 * Instantiate libraries...
 */
var sr = ScrollReveal(config)
var scrollbar = Scrollbar.init(elem)

/**
 * Link the ScrollReveal delegate (event handler) to
 * the Smooth ScrollBar synthetic event listener...
 */
scrollbar.addListener(function (status) {
    var fakeEvent = { type: scroll }
    sr.delegate(fakeEvent)
})
```

From what I can tell, this is as far as I can take you—this _should_ link the synthetic scroll events from Smooth Scrollbar to the event handler of ScrollReveal... but I’m not sure if ScrollReveal will still correctly determine element visibility.

Let me know what you find.

**Comment by grahammcuk** [comment]
Thanks @jlmakes , this is really helpful. I'll let you know how I get on...

**Comment by jlmakes** [comment]
Any updates on this @grahammcuk ? I’m curious if you were successful, just in case anyone in a similar position stumbles across this issue.

**Comment by grahammcuk** [comment]
I struggled to be honest @jlmakes - this was as far as I got... https://codepen.io/grahammcuk/pen/gRQNqP

Does this look like the implementation you suggested?

My javascript skills are limited though, so getting this working was probably out of my remit to begin with. Its a shame, this is the final piece of the puzzle for a new project!

**Comment by jlmakes** [comment]
So I [created an integration test](http://plnkr.co/edit/PKUAwZzS8mC1BbYLcZzt?p=preview) @grahammcuk, and I believe that currently it’s not possible to combine ScrollReveal with Smooth Scrollbar.

The Plunker as far as I can tell contains correct code, but I believe the reason ScrollReveal does not function as you scroll is due to how it checks element visibility: ScrollReveal uses element offset values, which does not factor in CSS transformations (like those used by Smooth Scrollbar uses).
