### ISSUE TITLE
Working with intervals triggers all animations at once, instead of on scroll

### ISSUE THREAD

**Issue by warrebuysse** [jlmakes/scrollreveal#358]
- Chrome/Safari (latest)
- Mac OS X
- ScrollReveal (latest) 3.3.6

```js
sr.reveal('.product-tile', {
	scale: 1,
	duration: 900,
	distance: '30px',
	easing: 'ease-out',
}, 50);
```

When using the "interval" integer after the options all the animations on the page are triggered at the same time, so theres no "reveal on scroll" anymore. Without the interval it works fine, but the interval is exactly the effect i'm going for.

Pen to demonstrate: https://codepen.io/studiotwist/pen/RgxmEy

**Comment by jlmakes** [comment]
You’re not alone!

This has come up quite a few times (#339, #305 #297 #272 etc.) and in short, this is a known limitation of the sequencer. The good news is that this is the signature improvement made to [ScrollReveal 4.0](https://github.com/jlmakes/scrollreveal/pull/323) which you can use today!

If you’d like, check out [what's different in v4](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md) and give the beta a try:
```
https://unpkg.com/scrollreveal@beta
```
It’s undergone 8 months of development (with 5 months in public beta), 98% backwards compatible, and it’s quite stable. Your feedback would be greatly appreciated, but if you prefer to wait, I expect the final release (and new website) will be out within a week or two.

_(To be candid, there’s just one remaining bug before I drop the beta tag.)_

**Comment by warrebuysse** [comment]
Alright, will jump on that train! Thanks!
