### ISSUE TITLE
Plugin not recognizing the duration value

### ISSUE THREAD

**Issue by SpencerMiller23** [jlmakes/scrollreveal#359]
**ScrollReveal 3.3.6**

I am using this plug in various places on a website I am working on. However, in one specific case the duration I am setting for these animations. I am also limiting the animations to just mobile screen sizes using jQuery. When viewing on desktop screen reduced to mobile size on any browser the animation looks fine. However when viewing on several different iPhones and iPads with Safari and Chrome, the animation does not factor in the duration I am setting.

```js
window.sr = ScrollReveal({ reset: false, mobile: true });

sr.reveal('.intro-body', {
    distance: "50px",
    scale: 1,
    viewFactor: 0.01,
    opacity: 0 });

if ($(window).width() <= 991) {
    sr.reveal('.full', {
        duration: 1000,
        distance: "0px",
        scale: 1,
        viewFactor: 0.7,
        opacity: 0
    });
}
```

Link to page: http://www.gohrvst.com/our-work

**Comment by jlmakes** [comment]
So am I understanding this correctly, `options.duration` is not working on mobile devices?

**Comment by jlmakes** [comment]
I loaded up your site on my iPhone and I see what you mean—the reveals occur almost instantly.

**Comment by SpencerMiller23** [comment]
Hi, I have fixed the errors that you pointed out and the problem still persists. I knew about those errors all along but they have not been affecting the website. I don't think this issue is closed yet and appreciate you trying to help me out with it.
