### ISSUE TITLE
Custom event on viewport visible?

### ISSUE THREAD

**Issue by IndexOverflow** [jlmakes/scrollreveal#36]
A great addition to scrollReveal would be the ability to trigger your own JS events on viewport visibility.

**Comment by Alaamasoud** [comment]
Hi,
can you please explain how it's possible to trigger the animation when element exit the viewport?

thanks in advance

**Comment by jlmakes** [comment]
@Alaamasoud you would have to use [`options.afterReset`](https://scrollrevealjs.org/api/after-reset.html)
