### ISSUE TITLE
es2015 module

### ISSUE THREAD

**Issue by shrpne** [jlmakes/scrollreveal#360]
Would be great if ScrollReveal would be written as an es2015 module.
And will have wrapped in UMD module only in dist.

So it will better fit to modern web applications, and will resolve issues like #218

**Comment by jlmakes** [comment]
Thanks for the feedback @shrpne.

ScrollReveal 4 is now available as an ES2015 module as `dist/scrollreveal.es.js` and will be available starting with `v4.0.0-beta.10`

**Comment by jlmakes** [comment]
Thanks for the feedback @shrpne.

An ES2015 module as `dist/scrollreveal.es.js` will be available starting with `v4.0.0-beta.10`
