### ISSUE TITLE
v4 - Use classes to properties to reveals

### ISSUE THREAD

**Issue by ekfuhrmann** [jlmakes/scrollreveal#366]
In the current stable version of SR, I was able to apply multiple classes with SR attributes to it.

So as an example, I'd have the following:

```js
var revealLeft = {
    duration   : 700,
    distance   : '30%',
    easing     : 'ease-in-out',
    origin     : 'left',
    scale      : 1,
    viewFactor : 0.5,
};
```

I'd then tie the reveal to a class, like so: `sr.reveal('.sr-left', revealLeft);`.  As expected, this would animate the section when it comes into view from the left.  

Occasionally, I'd want to delay certain elements, so I created a new sr.reveal class like the following: `sr.reveal('.sr-delay', { delay : 300 });`.

As an example of how this would look within the HTML, markup, see the following:

```html
<div class="card sr-left"></div>
<div class="card sr-left"></div>
<div class="card sr-left sr-delay"></div>
<div class="card sr-left"></div>
```

This would then reveal each card from the left, with the second-to-last one having a slight delay before animating in from the left.

Since v4, I've noticed that this no longer works. The delay class either does not work at all, or it removes the animation. It seems to now be a one or the other type deal, and I was wondering if there was any workaround or even if this was an unintended side-effect of another change?

**Comment by jlmakes** [comment]
You’re right that this does not work currently in v4—currently the `reveal()` calls on the same element do not combine (unlike v3). This change _was_ intentional when rewriting the code, but I’ve been thinking of adding it back due to some other in-development changes.

`4.0.0-beta.10` is coming soon, which will honor the v3 behavior you’re used to. As always, I appreciate the feedback @ekfuhrmann.

**Comment by ekfuhrmann** [comment]
I look forward to checking it out! Do you have any estimate time drop for when you expect it to be ready (such as in a week or more)?

**Comment by jlmakes** [comment]
I’m working full-time on it, so I expect sometime this week.

**Comment by ekfuhrmann** [comment]
Not a problem, was just trying to strategize on my end on whether or not to revert back to the previous stable build for the time being. With the possibility of an update later this week I'll hold off on any plans to revert.

Thank you again for being so responsive!

**Comment by jlmakes** [comment]
Finally got everything to play nice. New sequencer, alongside the restored element config behavior we’ve discussed above. Check it all out in the latest `v4.0.0-beta.10`, now on NPM:

`npm i scrollreveal@beta` or `https://unpkg.com/scrollreveal@beta`

**Comment by jlmakes** [comment]
You know what, I’m actually spotting some issues now—you may want to revert until `beta.11`.

**Comment by jlmakes** [comment]
`v4.0.0-beta.11` is out.

Fixed a bug in the sequencer logic, and an error with `options.container`. There‘s one outstanding edge case (that I won’t mention teehee) but it’s looking pretty good. I think you can expect one more beta release before this goes gold.

**Comment by ekfuhrmann** [comment]
Sounds great! I'll take it for a spin later today on my staging environment and report back with how it all goes.
