### ISSUE TITLE
On reveal not working.

### ISSUE THREAD

**Issue by ReMuSoMeGa** [jlmakes/scrollreveal#368]
I wrote a very simple test website to try and load my website images/sections

https://github.com/ReMuSoMeGa/scrollreveal

there is a class called `.more-left` that should fade in when 0.5 is revealed. No matter what I change this to, it does not work. Instead, everything loads at the exact same time. However, if I am scrolled to the very bottom and refresh -- things reveal on scroll when I scroll back up. Everything is backwards and wrong. Please tell me what I did wrong here.

**Comment by jlmakes** [comment]
Your page is missing a doctype declaration.

`<!DOCTYPE html>` must be present at the top of your file.

Related to #169
