### ISSUE TITLE
[Question] Elements outside of viewport being revealed

### ISSUE THREAD

**Issue by akroii** [jlmakes/scrollreveal#370]
OSX Sierra
Chrome 60.0.3112.101 (64-Bit)
ScrollReveal 3.3.1

If DOM is ready, elements being revealed, but they are not in viewport and outside of visible area. Every elements should be revealed on scroll if in viewport!

Whats going wrong? [http://bit.ly/2uYkC46](http://bit.ly/2uYkC46)

**Comment by jlmakes** [comment]
Hi @akroii 

It sounds a lot like you’re missing `height: 100%` on your `<body>` element.

Without this, your `<body>` will stretch to the entire height of the content… and so elements will be considered visible immediately (even if the window isn’t large enough).

**Comment by jlmakes** [comment]
I see.

ScrollReveal 3 does not apply `height: 100%` to the `<body>` for you. That seems to be the most common hole in the system that developers run into where elements reveal too soon.

I did notice quite a few errors in the console, perhaps it’s a conflict with a 3rd party library. I’ll take a second look at the site when it’s back up, I’m getting some errors from the site now…

> **Warning:** require(/var/virtual/newface/public/dev/system/initialize.php): failed to open stream: No such file or directory in **/var/virtual/newface/public/dev/index.php** on line **16**
>
> **Fatal error:** require(): Failed opening required '/var/virtual/newface/public/dev/system/initialize.php' (include_path='.:/usr/share/php-5.6.31/lib/php') in **/var/virtual/newface/public/dev/index.php** on line **16**

**Comment by akroii** [comment]
try again, please

**Comment by jlmakes** [comment]
@akroii You are using the v3 sequencer.

```js
sr.reveal('timeline-item', config, 250)
```

That `250` is the reveal **interval** and creates a sequence. Iin version 3, all elements in a sequence are triggered when any of them are visible. This has come on quite a few times… #367 #358 #342 #339 #305 etc...

The short answer is upgrade [version 4](https://github.com/jlmakes/scrollreveal/tree/development) (currently in [late-stage beta](https://github.com/jlmakes/scrollreveal/pull/323)), which has a brand new (and completely kick ass) sequencer.

**Comment by jlmakes** [comment]
@afalchi82 Some changes hit the v4 beta recently:

The `interval` parameter has been removed, and replaced with `options.interval`.

```js
// v3.x
var sr = new ScrollReveal();
sr.reveal('.item', { duration: 500 }, 200);
```

```js
// v4.x
ScrollReveal().reveal('.item', { duration: 500, interval: 200 });
```
