### ISSUE TITLE
Elements with 100% width never reveal?

### ISSUE THREAD

**Issue by ezeinis** [jlmakes/scrollreveal#373]
I have an html header tag in an image with a text that when is loaded from tablets it needs 2 lines whereas on desktop it needs 1 line

![screen shot 2017-08-30 at 3 35 45 pm](https://user-images.githubusercontent.com/19891292/29872967-667619da-8d9a-11e7-9982-64241f33d6b7.png)

![screen shot 2017-08-30 at 3 35 52 pm](https://user-images.githubusercontent.com/19891292/29872974-6b727816-8d9a-11e7-8b94-0264d3345cc9.png)

When the page is loaded from a device that is small enough for the text to appear on 2 lines it doesn’t reveal

![screen shot 2017-08-30 at 3 36 01 pm](https://user-images.githubusercontent.com/19891292/29873000-7dee9844-8d9a-11e7-9505-6eea5ccfc4a9.png)

I have a live demo but it is a work in progress for a client. If you really need an example I can set one page up.

Thanks for your time in advance!

- OSX
- Chrome 60.0.3112.113 / Firefox 54.0.1
- ScrollReveal 3.3.6

**Comment by jlmakes** [comment]
A working demonstration of the problem is essential for me to offer debugging help… and if this is not a bug, so that future developers will be able to learn from your issue.

**Comment by ezeinis** [comment]
http://cdb.pxworks.co/category

You can see the issue in the first banner under the main menu. Let me know if you need something else :)

**Comment by jlmakes** [comment]
I haven’t reproduced the issue on my own, but it appears that when the element you’re trying to reveal is the same width as the window—it is never revealed. I don’t know what all is happening on your page, but the solution appears to be simple:

**Add a non-100% width to your reveal targets to your smaller breakpoints.**

I’m marking this as unconfirmed until this can be reproduced with a [JSBin](https://jsbin.com).

**Comment by ezeinis** [comment]
Your solution worked out thanks! Tried to reproduce it to help you but i couldnt, almost the exact code https://output.jsbin.com/sekijot/ 

Thanks for your time anyway!
