### ISSUE TITLE
scrolling too fast will cause no display

### ISSUE THREAD

**Issue by Yiiu** [jlmakes/scrollreveal#374]
windows 10
chrome 60.0.3112.113
version: 3.3.6
demo: http://dc.raffhk.com/products

**Comment by jlmakes** [comment]
You’re using an old beta.

That page is running ScrollReveal `4.0.0-beta.2`, not version 3; this bug has already been spotted in #341, and squashed in `4.0.0-beta.6`. Since you are already using version 4, **I strongly recommend that you upgrade to the latest beta version `4.0.0-beta.14`.**

**Comment by Yiiu** [comment]
@jlmakes thank you~
