### ISSUE TITLE
Using Sync() from within Vue component?

### ISSUE THREAD

**Issue by kikky7** [jlmakes/scrollreveal#376]
I display (with vue.js `v-for` attribute) some number of items on the page with class `.reveal` (which adds reveal effect on scroll) and revealing works fine for those items.

Clicking the button, I append additional data to the same vue object, but every of those items is already revealed. I tried to use `sr.sync()` method after the append code, but no success.

Then I tried `sr.init()` method, but I am getting the error that sr.init is not a function. Is there any way to reveal dynamically added items using vue.js `v-for` attribute?

```js
if (result.length > 0) {
	$.each(result, function () {
		newGames.push(this);
	});
	console.log(sr);
	sr.init();
}
```

`console.log(sr)` successfully outputs the `sr` object in the console. `newGames` is a vue.js variable which is used inside `v-for`.

> Ubuntu 16.04
> Chrome 61
> ScrollReveal 3.3.6

**Comment by jlmakes** [comment]
I'm somewhat familiar with Vue, but I'm having trouble fully understanding the problem. Would it be possible for you to create a live demonstration of the problem using [JSBin](http://jsbin.com/?html,js,output)?

**Comment by kikky7** [comment]
It's an old thread, but I confirm that sr.sync() should be used within updated lifecycle hook.
