### ISSUE TITLE
Breaks responsive design in mobile browsers

### ISSUE THREAD

**Issue by Ghost180195** [jlmakes/scrollreveal#377]
ScrollReveal version: 3.3.6
You can test in this page:
http://liteslim.kz/
Tested in Opera 43.0.2246.121183, Google Chrome 61.0.3163.98
Tested in Android 4.2.2 and Android 6.0
If i set mobile: false then responsive design works fine.

**Comment by jlmakes** [comment]
Seems as though `overflow-x: hidden` is only on `<body>`, but missing from `<html>`; to be honest, it wasn't clear to me that it has to be present on both, but this is what removed the unwanted space in your mobile layout.

```css
html, body {
    overflow-x: hidden;
}
```

I’ll try to make this information more available (or perhaps handle this automatically), as this has come up many times before.

Duplicate: #50 #318 #328 #369

**Comment by RICK-1994-ITAC** [comment]
Resolveu meu problema. coloquei overflow-x: hidden; em body e html, e resolveu a quebra
