### ISSUE TITLE
Not working when overflow-x:hidden

### ISSUE THREAD

**Issue by tobsut97** [jlmakes/scrollreveal#379]
Hey guys,

when I set `overflow-x: hidden` on `<body>` the ScrollReveal animations don't work anymore.

I am using Chrome and ScrollReveal v3.3.6.

**Comment by jlmakes** [comment]
Can you link to a demonstration of the problem?

**Comment by tobsut97** [comment]
[This](www.ferienwohnung-flatz.at) is the url to the website. 
https://github.com/tobsut97/FerienwohnungFlatz this is the repository, I think the problem is either in the index.php or style.css file.

**Comment by jlmakes** [comment]
I see `overflow-x: hidden` on the bottom, and ScrollReveal seems to be working fine. Is there a particular element or section of the page that is not behaving as you would expect?

**Comment by tobsut97** [comment]
Decrease the viewport size to around 1280px and then its not working
anymore.

**Comment by jlmakes** [comment]
I see.

You’re including ScrollReveal 3 at the bottom like this:

```html
<script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
```

Can you do me a favor and try the ScrollReveal 4 beta?

```html
<script src="https://unpkg.com/scrollreveal@beta"></script>
```

**Comment by tobsut97** [comment]
Did it, same issue as before.

**Comment by jlmakes** [comment]
ScrollReveal 4 exposes a lot more information which can help debugging; can you upload that change to the site so I can take a closer look?

Also, recreating this issue using [JSBin](https://jsbin.com) would help confirm the bug.

**Comment by tobsut97** [comment]
Okay, uploaded the change to the live version of the site. 
Will try to recreate this issue in JSBin.

**Comment by jlmakes** [comment]
Thanks for raising the issue @tobsut97, cause I’m actually having the same problem locally. Except to my knowledge, this only started very recently for me.

I thought it was an update to Chrome, but I'm having some issues across browsers.

**Comment by tobsut97** [comment]
Makes sense. So how do I fix this? Do I have to remove the overflow-x:hidden?

**Comment by jlmakes** [comment]
Well, the `overflow-x: hidden` elimintates unwanted scrollbars/extra space on mobile... particularly when using reveal animations that enter from the sides; if you aren‘t worried about that, then in your case, the simple solution is to remove the `overflow-x` property.

**Comment by tobsut97** [comment]
The problem is that my site does some weird things on mobile when I remove the overflow-x property. So I either have to figure out a workaround for this or I have to keep the overflow-x property and we have to figure out a solution.

**Comment by jlmakes** [comment]
Well, I’m working on ScrollReveal full-time, and this bug is a priority.

For you, what if you take `overflow-x: hidden` off of the body, and wrap the content in a div that has `overflow-x: hidden` instead... does that get you anywhere?

**Comment by tobsut97** [comment]
YES! Thanks so much. 👍

**Comment by jlmakes** [comment]
This is actually a Webkit bug @tobsut97.... it seems to be the combination of:

- Height 100% set on `<html>`
- Any overflow property set on `<html>`

This results in `window.pageYOffset` and `document.documentElement.scrollTop` to **always** return `0`.
