### ISSUE TITLE
Empty space between elements after the animation is complete in Firefox

### ISSUE THREAD

**Issue by Ghost180195** [jlmakes/scrollreveal#380]
OS version: Windows 10
Mozilla Firefox version: 56
ScrollReveal version: 3.3.6
Codepen link: https://codepen.io/anon/pen/PJeJGY

The problem appears if the element's height is odd. If I set 
`section {
	height: 480px;
}`
everything will be fine.

![firefoxbug](https://user-images.githubusercontent.com/31181880/31377874-f41172ec-adc2-11e7-83b5-5a34798eb408.gif)

**Comment by jlmakes** [comment]
Thanks for taking the time to provide these details.

What you’ve highlighted are rounding errors, unspecific to ScrollReveal. Most browsers round CSS property values to integers, but CSS Transform relies on [GPU compositing](https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome), which behave differently; sub-pixel values are not rounded, and can result in blurry text/images or small gaps between elements (as you've shown here).

The straight forward answer is to not use sub-pixel values, or values that will result in a sub-pixel (such as `translateY(-50%); height: 101px`).

But for example, if the height of an element is dictated by an image, you might accidentally stumble into this problem. One solution is to use [ScrollReveal 4 (beta)](https://unpkg.com/scrollreveal@beta), which removes generated styles when reveal animations complete; once the CSS transform styles are removed, the rounding errors disappear. The only caveat is that you cannot use `options.reset` if you want reveals to complete.

**Comment by Ghost180195** [comment]
Thanks for your information!
