### ISSUE TITLE
Reveal from bottom on scroll down and from top on scroll up

### ISSUE THREAD

**Issue by antoniocosta** [jlmakes/scrollreveal#384]
Is it possible?
I have been fiddling but can't find a way to do it. I am guessing origin or distance would have to be reversed depending on scroll direction?
Please let me know... and thanks so much for the great work put into this!

**Comment by jlmakes** [comment]
Hey Antonio,

ScrollReveal presently has no built-in awareness of scroll direction. I think `options.scale` is the closest approximation of getting elements to reveal "from the top on scroll up, from the bottom on scroll down". ([Demo](http://jsbin.com/hideqocati/edit?html,output))

*For what it's worth, I can point you to the correct part of the source to begin adding this functionality if you'd like to take a stab at forking the repository and creating a custom build.*

**Comment by antoniocosta** [comment]
Hi Julian,
Yeah... I noticed you achieve similar effect with scale. Scaling doesn't look that great when there's text though.
Yes... please do point me to the correct part of the source and I'll take a stab at it! I think it's worth a shot.
Here's roughly what I am trying to do: https://jsfiddle.net/abmc/9d0qpsb0/

**Comment by antoniocosta** [comment]
PS: On a slightly separate note... too bad passing scale: "1, .5" for only Y scaling doesn't work anymore on the new beta.

**Comment by jlmakes** [comment]
I can see why you want this behavior, the end result should look awesome.

### Tracking Scroll Direction.

You’ll want to start right here:
`/src/instance/functions/delegate.js` on [line 16](https://github.com/jlmakes/scrollreveal/blob/v4.0.0-beta.19/src/instance/functions/delegate.js#L16)

That will put you within this loop:

```js
each(this.store.containers, container => {
	if (stale) {
		container.geometry = getGeometry.call(this, container, true)
	}
	container.scroll = getScrolled.call(this, container) // here!
})
```

I fiddled around and came up with this:

```js
each(this.store.containers, container => {
	if (stale) {
		container.geometry = getGeometry.call(this, container, true)
	}
	const scroll = getScrolled.call(this, container)
	if (container.scroll) {
		container.direction = {
			x: Math.sign(scroll.left - container.scroll.left),
			y: Math.sign(scroll.top - container.scroll.top),
		}
	}
	container.scroll = scroll
})
```

I'd guess that you probably only have one container, but regardless, they are all stored within the object `ScrollReveal().store.containers`; each one will end up looking something like this:

```js
{
	id: 2,
	node: <html>,
	geometry: {
		bounds: { top: 0, right: 420, bottom: 1446, left: 0 },
		height: 1446,
		width: 420,
	},
	scroll: { top: 360, left: 0 },
	direction: { x: 0, y: -1 }, // this is new!
}
```

Where `1` indicates scrolling down/right, and `-1` indicates scrolling up/left.

**Comment by jlmakes** [comment]
### Applying The Right Animations

This is the part I think it gets complicated to bake into ScrollReveal. I think instead, you'd want to use ScrollReveal just to track visibility and provide callbacks... but not to create/apply the styles automatically.

Here is one way to do that:

```js
```

**Comment by jlmakes** [comment]
### Applying The Right Animations

This is the part I think it gets complicated to bake into ScrollReveal. I think instead, you'd want to use ScrollReveal just to track visibility and provide callbacks... but not to create/apply the styles automatically.

Here is one way to do that:

```js
var noEffect = {
	delay: 0,
	distance: '0',
	duration: 0,
	easing: 'linear',
	opacity: null,
	origin: 'bottom',
	rotate: { x: 0, y: 0, z: 0, },
	scale: 1,
	container: this.defaults.container,
	desktop: this.defaults.desktop,
	mobile: this.defaults.mobile,
	reset: true,
	useDelay: 'always',
	viewFactor: this.defaults.viewFactor,
	viewOffset: this.defaults.viewOffset,

	afterReset: function (el) {},
	afterReveal: function (el) {},
	beforeReset: function (el) {}, // fill me in
	beforeReveal: function (el) {}, // fill me in
}

ScrollReveal().reveal('.items', noEffect)
```

This `reveal()` effectively won't do anything, but it does give you access to callbacks.

If you create your own CSS animation/transition classes, you can apply them based on the container's direction property. Here’s an example of how you might implement those callbacks:

```js
const beforeRevealCallback = el => {
	const id = el.getAttribute('data-sr-id')
	const containerId = ScrollReveal().store.elements[id].containerId
	const container = ScrollReveal().store.containers[containerId]

	if (container.direction > 0) {
		el.classList.add('animateFromBottom')
	} else {
		el.classList.add('animateFromTop')
	}
}

const beforeResetCallback = el => {
	el.classList.remove('animateFromBottom')
	el.classList.remove('animateFromTop')
}
```

**Comment by jlmakes** [comment]
Now, I haven't tested this implementation all the way through, but this should hopefully give you a solid start at achieving the effect you'd like.

> PS: On a slightly separate note... too bad passing scale: "1, .5" for only Y scaling doesn't work anymore on the new beta.

This is because instead of passing `options.scale` into a template string like `"scale(" + options.scale + ")"`, ScrollReveal 4 generates CSS Transform matrices—so that hack no longer works 😉

If you'd like, you can create a new issue to request that feature be added. If it can garner some community support, I would be easy to implement.

**Comment by jlmakes** [comment]
The suggested code fragment for **Tracking Scroll Direction** has been baked into `beta.20`. It's only a few lines of code, and I think it's a pretty cool way to allow developers to hack clever solutions like what you've detailed here.

**Comment by sebszocinski** [comment]
Hey guys, I've been looking for the same thing, and have tried your code above @jlmakes and noticed a small bug.

`if (container.direction > 0) {` should be `if (container.direction.y > 0) {`

Works for me! (so far...)

**Comment by jlmakes** [comment]
@sebszocinski Nice catch. I updated the pseudo code with:

```js
if (container.direction && container.direction.y > 0) {
	el.classList.add('animateFromBottom')
} else {
	el.classList.add('animateFromTop')
}
```

**Comment by antoniocosta** [comment]
Whoa!!! :)
Here's my stab at that pseudocode: https://jsfiddle.net/abmc/oaxmma6y/
Just had to comment all the `this.defaults.*` props to get rid of undefined errors.

**Comment by jlmakes** [comment]
@antoniocosta Nice!

You're totally right about the undefined errors with `this`, that's just my brain dropping the ball. I updated my earlier comment with a note on the erroneous lines.

**Comment by jlmakes** [comment]
@antoniocosta Nice!

You're totally right about the undefined errors with `this`, my brain done did a bad. I updated my earlier comment with a note on those erroneous lines, and how to fix them.

**Comment by rh-erivera** [comment]
Hey guys, Ive been able to achieve this affect with the following code: 
```
function scrollUp(el) {
  ScrollReveal().reveal('.med-img', { origin: 'top', afterReveal: scrollDown })
}
function scrollDown(el) {
  ScrollReveal().reveal('.med-img', { origin: 'bottom', afterReveal: scrollUp })
}
ScrollReveal().reveal('.med-img', { afterReveal: scrollUp })
```
I am using this on a SPA with multiple references to `.med-img` that are dynamically generated. So the problem right now is that the origin alternates as I scroll past each `.med-img`. Only solution I can think of is giving each piece content a unique ID. Any ideas for a more elegant solution?

**Comment by eiranix** [comment]
@jlmakes Another refinement to your if statement there is to make it pick the correct direction on first load:
```
	if (container.direction) {
		if (container.direction.y > 0) {
			el.classList.add('animateFromBottom');
		} else {
			el.classList.add('animateFromTop');
		};
	} else {
		if(el.getBoundingClientRect().top > 0) {
			el.classList.add('animateFromBottom');
		} else {
			el.classList.add('animateFromTop');
		};
	};

```

**Comment by BenRacicot** [comment]
This is awesome! Anyone have a working example?

**Comment by antoniocosta** [comment]
Quite old but try this example: https://jsfiddle.net/abmc/oaxmma6y/
