### ISSUE TITLE
Override Style Attribute

### ISSUE THREAD

**Issue by discoveryjames** [jlmakes/scrollreveal#386]
ScrollReveal overrides the style attribute if there are already properties applied to it.

This can cause other jQuery libraries to conflict.

As a workaround, I use an extra wrapper div to apply ScrollReveal to, but it might be better if ScrollReveal was aware of existing style attributes.

**Comment by jlmakes** [comment]
ScrollReveal does preserve inline styles, but it will overwrite CSS Transform or Transition styles with its own. As you've pointed out, wrapping elements in a `<div>` and revealing that instead solves the problem.

ScrollReveal 4 (beta) now also preserves CSS Transform and Transition styles.

If you're running into issues, it's probably the order of your scripts; ScrollReveal's `reveal` method should be invoked after other 3rd parties have applied their styles.

**Comment by jlmakes** [comment]
[ScrollReveal does preserve inline styles](http://jsbin.com/yuwubefebu/1/edit?html,output), but version 3 will overwrite CSS Transform or Transition styles with its own. As you've pointed out, wrapping elements in a `<div>` and revealing that instead solves the problem.

ScrollReveal 4 (beta) now also preserves CSS Transform and Transition styles 🎉

If you're running into issues, it's probably the order of your scripts; ScrollReveal's `reveal()` method should be invoked after other 3rd parties have applied their styles.

If you're using the ScrollReveal 4 beta already, there was a recent bug introduced in `beta.17` with inline styles that was patched just an hour ago; in this case, please upgrade to `beta.19`.
