### ISSUE TITLE
Set opacity to 1 for firsts items after an isotope filtering

### ISSUE THREAD

**Issue by blackspirit** [jlmakes/scrollreveal#387]
Hi,

First thanx for ScrollReveal who is so smooth and nice to use !

Sorry, it's not an issue but something I want to change.
I am using ScrollReveal on an isotope filtered portfolio (no page reload) in a php page. All is fine. But when I filter my items, I don't know how to offset some items that are hidden before scrolling. 
So I have a blank page in some cases.

So, I want to force firsts items after filtering to be visible, like a first load.
Is it possible ? Can you help me to find a solution ?

Best regards

Valery

**Comment by jlmakes** [comment]
Hi Valery,

There's not much I can do in this case without a demonstration. If you can you create a [JSBin](http://jsbin.com/?html,js,output) showing how far you’ve gotten, I'd be happy to contribute to help you achieve the behavior you're after.

**Comment by blackspirit** [comment]
Thanx for the answer :)

Well, i have this code
`sr.reveal('.revealportfoliogrid', { // portfolios items
                duration: 450 
            });`

It's working fine ;)
And with Scrollreveal it's definitely better with a fluid load of my items...
- - -

In a masonry filtered grid portfolio like this one https://www.lapresseaufutur.com/exposants.html
I can filter my grid without reloading the page.

The problem is that when I filter my items, some of them are hidden with scrollreveal. So, the question is : how can I force scrollreveal to show this item after filtering ? Maybe an action on the filters buttons ?

**Comment by jlmakes** [comment]
Ah yes, I understand.

Since ScrollReveal is listening for `scroll` and `resize` events, one way to force it to run the event handler (which decides when to apply styles), is to [manually trigger an event](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent):

```js
window.dispatchEvent(new MouseEvent('scroll'));
```

I assume you’re using Isotope (because you mentioned masonry filtered grid), so you’d need to call this within an Isotope callback; after a quick look through the source, it looks like you can do something like this:

```js
var iso = new Isotope(...);

iso.once('arrangeComplete', function () {
    window.dispatchEvent(new MouseEvent('scroll'));
});
```

It’s up to you to confirm browser support and implementation details, but this is the general idea.

**Comment by jlmakes** [comment]
I’d also like to mention, for [ScrollReveal 4 (beta)](https://unpkg.com/scrollreveal@beta) users, v4 exposes its event handler as the `delegate` instance property, so there’s no need to rely on simulating events.

> Plus, `delegate` has bound `this` to the instance, so you don't even need to invoke it within an anonymous function—simply pass it directly as the callback.

```js
var iso = new Isotope(...);

iso.once('arrangeComplete', ScrollReveal().delegate);
```

Again, the general idea is still the same. [See what's new in 4.0](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md)

**Comment by blackspirit** [comment]
Ok,
I have done this :
`$('#filter_all').click(function() {
                            $('html, body').animate({
                                scrollTop: '+=1'
                            }, 500);
                        });`

It's not an elegant way to do this...but it works ;)
Thanx for your help
