### ISSUE TITLE
scrollReveal on click?

### ISSUE THREAD

**Issue by scolarossi** [jlmakes/scrollreveal#389]
I'm having trouble getting scrollReveal to display after clicking a button. For example, I'll click a button on my page, and have it fadeIn with jQuery, making the full div visible. However, the elements using scrollReveal won't display until I scroll.

I've done a search through the issues, and have tried a few that I think would work, but am having no luck. 

Is there a way to call scrollReveal to see if any elements should be visible?

**Comment by jlmakes** [comment]
Wouldn’t tell from the issue title, but this actually just came up in #387

See [my response](https://github.com/jlmakes/scrollreveal/issues/387#issuecomment-338489798) and let me know if you have questions.

**Comment by scolarossi** [comment]
That seems to have worked. Thank you so much! I have been trying to figure that out for so long!
