### ISSUE TITLE
Gradual opacity increase/decrease on scroll down

### ISSUE THREAD

**Issue by mateustav** [jlmakes/scrollreveal#392]
Hi there,

This plugin is really really awesome. I really like it because it has no dependencies. 👌

I have a question though. Does this plugin allow a gradual increase of opacity on scroll down (and decrease while scrolling up) so image fades as you scroll and not fades in or out entirely when it reaches or leaves the viewport? [Like this effect for instance](https://codepen.io/mateustav/pen/BmBRLV)

If possible, great. I'm trying to figure it out by myself with no luck so far but if not, I leave this ticket as a feature request!

**Comment by jlmakes** [comment]
Thanks for the kind words Mateus.

Nothing like what you describe is baked into ScrollReveal: there is no notion of "percentage scrolled", or driving animation progress with the scroll bar.

However, you should take a look into [ScrollMagic](http://scrollmagic.io/), it’s specifically designed for such behavior.
