### ISSUE TITLE
Simple animation won't work

### ISSUE THREAD

**Issue by hkyq** [jlmakes/scrollreveal#393]
So I'm having a bit of a problem. I'm new to JS, and I don't really see why this code isn't working. 
https://repl.it/Nbob/1

There weren't any errors in the console, and the code was taken from the readme.

**Comment by jlmakes** [comment]
Hey Harry,

Please read the section [Order Matters](https://github.com/jlmakes/scrollreveal/tree/master#41-order-matters).

The code itself looks correct, but you're invoking ScrollReveal methods in the `<head>` of the page—which is before the content within the `<body>` has loaded; that means when you call `sr.reveal('.foo')`, no elements exists yet with the class `foo`.

Check this out:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <script>
    var myDiv = document.querySelector('.foo')
    console.log(myDiv)
  </script>
</head>

<body>
  <div class="foo"> Foo </div>
</body>

</html>
```

The console will output `null`. You can [see this example live](https://repl.it/Nbob/3).

But by changing _when_ our JavaScript runs (by moving it after the content we expect it to have access to), we get the output we're looking for:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
</head>

<body>
  <div class="foo"> Foo </div>
  
  <script>
    var myDiv = document.querySelector('.foo')
    console.log(myDiv)
  </script>
</body>

</html>
```

The console will output `HTMLDivElement`. You can [see this example live](https://repl.it/Nbob/5).

**Comment by hkyq** [comment]
Ok, thanks!
