### ISSUE TITLE
Issue with Bootstrap modals

### ISSUE THREAD

**Issue by dkapexhiu** [jlmakes/scrollreveal#396]
I'm having an issue with bootstrap modals. After i add the scrollreveal script in the head tag and i load the page, the modal opens blurred in a container window and i can not interact with the modal until i refresh the page. Has someone else experienced this issue? What can i do for it?

**Comment by jlmakes** [comment]
If you can recreate the issue using [JSBin](https://jsbin.com) I'll help you debug it.

**Comment by dkapexhiu** [comment]
Yes, thank you very much,
Here's the link on codepen: https://codepen.io/dkapexhiu/pen/OOzJxN

**Comment by jlmakes** [comment]
I don't understand what the issue is, and there's a little too much going on in that Codepen.

Luckily, I found a simple fix: upgrade to [ScrollReveal 4](https://github.com/jlmakes/scrollreveal/tree/development).

```diff
- <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
+ <script src="https://unpkg.com/scrollreveal@beta/dist/scrollreveal.min.js"></script>
```

Quite a bit has been improved, but also keep in mind the [license has changed](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md); if that's doesn't work for you, I’ll need a simpler (much more isolated) demonstration of the problem using v3 to help you.

**Comment by dkapexhiu** [comment]
Thank you for the fix. Now the modal is working, but it seems that scrolling is not working. 
I've put in the header of html:
`<script src="https://unpkg.com/scrollreveal@beta/dist/scrollreveal.min.js"></script>
<script>window.sr = ScrollReveal();</script>`
And in the end of body:
`<script>sr.reveal('.featurette', {duration: 200}, 50);</script>`
In the beta does have changed the way to call functions?

**Comment by jlmakes** [comment]
> In the beta does have changed the way to call functions?

No, ScrollReveal 4 should be a drop-in replacement.

> Thank you for the fix. Now the modal is working, but it seems that scrolling is not working.

It was a fluke that I tried ScrollReveal 4 and it appeared to fix the layout issue. I'm not sure how to help without more information, and a clear reproduction of the problem.

**Comment by dkapexhiu** [comment]
I updated with some other text the codepen: https://codepen.io/dkapexhiu/pen/OOzJxN

ScrollReveal 4 doesn't work. The divs are not appearing and disappering instantly. 
I am using bootstrap, jquery and popperjs. 
With ScrollReveal 3 the effect is more visible: the divs appear and disappear instantly. 

Can you test it?

**Comment by jlmakes** [comment]
I know less than you do about this, I don't use Bootstrap jQuery or PopperJS. If you prefer ScrollReveal 3, that's fine—let's stay focused on the modal issue.

Your modal content is _inside_ `.featurette`, but it could live anywhere—and in this case it's causing problems for whatever reason. If you move your modal content into the `<body>` the z-index issue seems to go away.

**Comment by dkapexhiu** [comment]
How can i move it? Can you show me code, please?

**Comment by jlmakes** [comment]
https://codepen.io/anon/pen/xPpXRq?editors=1000

**Comment by dkapexhiu** [comment]
Ok, thank you. I found a way to isolate the modal and bypass the problem! Congratulations to the project!
