### ISSUE TITLE
Question: Is there a way to reveal elements diagonally?

### ISSUE THREAD

**Issue by atlas24** [jlmakes/scrollreveal#398]
I have some images I would like to reveal coming from the top middle of the screen to the lower right using a diagonal reveal. Is this possible using scrollreveal?

**Comment by jlmakes** [comment]
This has come up before as a feature request (#123), but it's _currently not possible_.

`4.0` is launching soon, and I don't think any new features will make it into that release. 

I took a quick look at how this could be implemented, and I think only [~45 lines](https://github.com/jlmakes/scrollreveal/blob/4e501aabde006c406d25c2005c0216aac38a043d/src/instance/functions/style.js#L41-L87) need refactoring—that's not bad, and I like the idea; I‘ll take a second look at this for a `4.1` release in early 2018.

Thanks @atlas24.

**Comment by jlmakes** [comment]
This has come up before as a feature request (#123), but it's _currently not possible_.

`4.0` is launching soon, and I don't think any new features will make it into that release. 

That said, I did just take a quick look at how this could be implemented, and it doesn't seem too bad. I like the idea, so I‘ll take a second look at this for a `4.1` release in early 2018.

Thanks @atlas24

**Comment by SRTM** [comment]
Agreed, that and a simple horizontal option would be great.

**Comment by jlmakes** [comment]
Would you explain more of what you have in mind?

**Comment by SRTM** [comment]
@jlmakes Currently, when you use the 'distance' option, that only alters the vertical distance (y-axis) of an element. It would be great if you could also alter the horizontal distance (x-axis).
Ie. Have elements fade in from the left or right, rather than up or down. Usually I have to rely on adding a separate custom css animation for that.
Thanks :)

**Comment by jlmakes** [comment]
@SRTM [Check this out](http://jsbin.com/donivizovu/edit?html,css,output)
