### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by ryangittings** [jlmakes/scrollreveal#399]
Hey,

I'm trying to figure how if I have multiple components on a page, how I can get them to ScrollReveal in their own entity?

I'm using `sr.reveal('.callout');`, and I have two callouts at different positions on the page, but only the first animates. I'm trying to make each component have it's own reveal animations, to keep consistency.

Any advice really appreciated, many thanks!

**Comment by jlmakes** [comment]
What version of ScrollReveal are you using?

**Comment by ryangittings** [comment]
3.3.6 :)

**Comment by jlmakes** [comment]
It’s possible `height: 100%` is missing from the `<body>`. That can cause elements that are out of view (on page load), to reveal anyway—so by the time you scroll to them, there's no animation to see.

That sounds a lot like what you've described to me.
