### ISSUE TITLE
How do i make animation pull down?

### ISSUE THREAD

**Issue by knstyle** [jlmakes/scrollreveal#400]
Hi, i'm trying to achieve this kind of animation of these vertical lines in this website: https://www.wix.com/website-template/view/html/1967

I think the idea to do this is set height 0 before reveal. But i don't know how to do that with scrollreveal.
And also, how to do reverse which means pulling up the line?

**Comment by jlmakes** [comment]
I don't think ScrollReveal will help you create the animation effect on the center line.

**Comment by knstyle** [comment]
Thanks for the answer. Actually i don't need the line follows on scrolling. Simply just do the effect when it's in screen.
So this kind of effect/animation is not supported by Scrollreveal?

Not relevant for this issue, but would you recommend me a simple smooth parallax background effect jquery? I have tried Stellar but it's very jerky on chrome.

**Comment by jlmakes** [comment]
ScrollReveal uses hardware accelerated properties, i.e. `opacity` and `transform`; there is no support for animating `height`, so it's up to you to simulate the effect another way.

**Comment by Glenn-Accomplice** [comment]
Perhaps instead of height you could use transform scale? Like start from a scale of 0 and end up with 1, putting the transform origin at the top. If you're looking to duplicate that Wix example you could put a white background on the text so you can transition one line instead of two.
