### ISSUE TITLE
Run on Electron

### ISSUE THREAD

**Issue by kanalasumant** [jlmakes/scrollreveal#401]
Thanks for this super cool animation library.

I wanted to ask if anyone could suggest me how to load ScrollReveal on Electron, since Electron doesn't [directly support](https://ourcodeworld.com/articles/read/202/how-to-include-and-use-jquery-in-electron-framework) JavaScript. However, that didn't work for me.

Could anyone suggest something to try?

**Comment by jlmakes** [comment]
I can't say for sure, but I took a look at the blog post. You tried something like this already?

```bash
npm install scrollreveal --save
```
```html
<script>window.ScrollReveal = require('scrollreveal')</script>
```

**Comment by kanalasumant** [comment]
Yes. Now it works. Didn't try your method but understood that electron uses **node**, so **commonJS** at play here.


Also [this](https://stackoverflow.com/questions/32621988/electron-jquery-is-not-defined) worked.
