### ISSUE TITLE
Visible onload

### ISSUE THREAD

**Issue by jonatangrim** [jlmakes/scrollreveal#402]
Element without the viewport is set to visible onload without the animation when scrolling, but elements within viewport onload works. Version is 3.3.6

scrollreveal.min.js i loaded in header.

Content is mulitple <p>

Before body:
`window.scrollreveal = ScrollReveal();
scrollreveal.reveal('p', {
    viewFactor: 0.6,
    mobile: true
});`

**Comment by jonatangrim** [comment]
Works with v4.0.0-beta.24.
Can I get it to work with 3.3.6?

**Comment by jlmakes** [comment]
Not sure I understand.

Have you tried setting `height: 100%` on the `<body>`? This is a common solution to similar problems, that version 4 does for you automatically.
