### ISSUE TITLE
Possibility to pass not only NodeList, but array to

### ISSUE THREAD

**Issue by makedonec88** [jlmakes/scrollreveal#405]
Hello.

I'm using ScrollReveal along with Vue.js, and I have list of elements I want to animate. I can get the elements directly from Vue, but it's an `Array` of `Nodes` which ScrollReveal doesn't seem to support. So for now I have to use `document.querySelectorAll`.

Is it possible to pass an `Array<Node>` to ScrollReveal?

Thanks.

**Comment by jlmakes** [comment]
Hey Ali!

This feature already exists in [ScrollReveal 4](https://unpkg.com/scrollreveal@beta)!

Don't let the beta tag throw you, it's more robust than version 3—but until the new documentation is finished, the tag stays. Practically speaking though, it's a [drop-in upgrade](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md).

**Comment by jlmakes** [comment]
Hey Ali!

This feature already exists in [ScrollReveal 4](https://unpkg.com/scrollreveal@beta)!

Don't let the beta tag throw you, it's more robust than version 3—but until the new documentation is finished, the tag stays. Practically speaking though, it's a [drop-in upgrade](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md).

**Comment by jlmakes** [comment]
Hey Ali!

This feature already exists in [ScrollReveal 4](https://unpkg.com/scrollreveal@beta)!

Don't let the beta tag throw you, it's more robust than version 3—but until the new documentation is finished, the tag stays. Practically speaking though, it's likely a [drop-in upgrade](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md).
