### ISSUE TITLE
scroll reveal causing horizontal scrollbar until elements are scrolled on.

### ISSUE THREAD

**Issue by alenart91** [jlmakes/scrollreveal#406]
Is there something I should add to my file to get rid of this issue? If I delete my reveal js file everything works perfectly. It creates a horizontal scrollbar until all the elements are revealed then the scrollbar disappears. 

I'm using version 3.1.4 and noticed this problem in chrome and mobile. Haven't checked any other browsers.

**Comment by jlmakes** [comment]
Please see #377
