### ISSUE TITLE
Taking into account display: none elements

### ISSUE THREAD

**Issue by bakura10** [jlmakes/scrollreveal#407]
Hi :),

I'm currently using the beta of v4 (but been able to reproduce it on v3 as well) when using a sequence.

I have a sequence with a grid of items :

```
              ITEM 1
ITEM 1 BIS | ITEM 2 | ITEM 3 | ITEM 4
```

On desktop, ITEM 1 is visible, but Item 1 bis is hidden (ITEM 1 has a different markup and can't be achieved otherwise), while on mobile, Item 1 is hidden but Item 1 bis is visible.

The issue when using the sequence is that ScrollReveal will still take into account the display: none item and there will therefore be a larger delay between Item 1 and Item 2 than Item 2 and Item 3.

I think that ScrollReveal should ignore any elements that are set to display: none for the sequencer logic (by using getComputedStyle).

Or maybe there is a different way to achieve that or an option I've missed? :)

Thanks!

**Comment by bakura10** [comment]
Hi again,

The JSBin I've setup for the other question apply here as well. I've simply increased the animation time so it's easier to spot: https://jsbin.com/ruhenifuzu/1/edit?html,output

As you can see the first image appears immediately, then there is an additional delay before the second visible item appears, as it seems ScrollReveal applied took into account the hidden element in the DOM (in second position).

**Comment by jlmakes** [comment]
Salut encore Michael,

> I think that ScrollReveal should ignore any elements that are set to `display: none` for the sequencer logic (by using `getComputedStyle`).

ScrollReveal does do a lot for you automatically, but in this case, I think it's the developers responsibility to figure out what elements to reveal—and let ScrollReveal figure out _how_ to reveal them.

_Here's one example of how you can handle this using a `node` array as the target (new in v4):_

```js
const nodes = document.querySelectorAll('.rect')

const target = 
	Array.prototype.slice.call(nodes) // convert nodelist to array
		.filter(node => getComputedStyle(node).display !== 'none')
	
const options = {
	reset: true,
	size: 0.9
}

ScrollReveal().reveal(target, options, 250)
```

J'espere que ça roule bien! 😀

See the [Live Demo on JSBin](https://jsbin.com/casuqem/1/edit?html,css,output).

**Comment by bakura10** [comment]
Merci beaucoup, ça devrait faire l'affaire :).
