### ISSUE TITLE
Color variant

### ISSUE THREAD

**Issue by cdmoro** [jlmakes/scrollreveal#409]
Hi! It would be nice if we have the possibility to set a color animation, during the reveal and set too a color after animation finish.

**Comment by cdmoro** [comment]
I found a good example of this behavior: https://sdras.github.io/array-explorer/ when the options are selected at the right of the screen appears two boxes with the color (and reveal) animation

**Comment by jlmakes** [comment]
Are you referring to the way the text is animated?

**Comment by cdmoro** [comment]
Yes, and the text color transition in particular

**Comment by jlmakes** [comment]
It's a cool effect, but for now I don't think it should be baked-in.

It’s possible developing the "color variant" effect as its own library, independent of ScrollReveal, may be prudent. (It would be trivial to integrate using ScrollReveal's callbacks, e.g: `options.afterReveal`)

Have you asked the creator if she created the effect from scratch? This library may already/soon exist.
