### ISSUE TITLE
window not found

### ISSUE THREAD

**Issue by strin** [jlmakes/scrollreveal#410]
When compiling for server side rendering with gatsby (https://www.gatsbyjs.org/docs/debugging-html-builds/), the `scrollreveal` package throws "window not found error".

**Comment by jlmakes** [comment]
Hmm, any idea how other DOM libraries handle this?

**Comment by jlmakes** [comment]
Hmm, any idea how other DOM libraries handle this?

**Comment by jlmakes** [comment]
Any idea how other DOM libraries are solving this? The advice I've given before is to inject DOM libraries using `<script>` tags, and defer to the client. (ScrollReveal uses the `window` a fair amount.)

Duplicate #304
