### ISSUE TITLE
Animations not working on a particular element

### ISSUE THREAD

**Issue by keloman** [jlmakes/scrollreveal#413]
Hello there! 

I have a very weird problem with ScrollReveal (not just the library, reveal effects in general).

For some reason, ScrollReveal works fine when I apply it to the `.one-rem-text` paragraphs but doesn't work if I apply it to the `a.image-bear` tag or the `img` tag inside it.

Opacity just stays at `0`, it never animates to `1`.

Repository is here: https://github.com/keloman/Parallax-tests.git

**Comment by jlmakes** [comment]
Can you update your repository to reproduce the issue?

Right now you have this [erroneous commit](https://github.com/keloman/Parallax-tests/commit/ca42fe43841ed817a7d4cfd85dd777795957db98#diff-b8ccc8d778c9219a5f7ce01b4e79110a) which throws:

```
Uncaught DOMException:
  - Failed to execute 'querySelectorAll' on 'Element': '.' is not a valid selector.
```

**Comment by keloman** [comment]
I've updated the repository,in the way you need,I hope.

And I've tried moving the ScrollReveal call to the `<head>` tag (like it is described in the README) but it didn't really work,at least when I tried it. 

I'm most definitely missing something since I've used this library before and it worked just fine then.

**Comment by jlmakes** [comment]
@keloman Well, loading the script in the `<head>` is about eliminating element flickering on page load.

I've found your problem, [please read](https://github.com/jlmakes/scrollreveal/issues/379#issuecomment-334201433).
