### ISSUE TITLE
Items already in view dont appear without scrolling on some browsers

### ISSUE THREAD

**Issue by flyke** [jlmakes/scrollreveal#414]
If a page is loaded with a scrollreveal element that is inside the viewport, it will immediatly start the animation, which is perfect.

However this does not work on:
- Firefox 57 on Windows 10
- Firefox 57 on macOS Sierra
- Safari 10.1 on macOS Sierra
Elements inside viewport are hidden after loading page untill you scroll.

(it does work with Safari and Firefox on macOS High Sierra)

**Comment by jlmakes** [comment]
Would you mind creating a [JSBin](http://jsbin.com) that demonstrates the problem?
