### ISSUE TITLE
How to reset from some other function?

### ISSUE THREAD

**Issue by dariodev** [jlmakes/scrollreveal#415]
Hello!
Is possible to call reset from some other function? For instance:
```js
window.sr = ScrollReveal({ useDelay: 'always', reset: false });
sr.reveal('.sr1', {
    // some config
});
sr.reveal('.sr2', {
    // some other config
});
// etc...
```
Now, when user reaches the bottom of the page, there will be a back-to-top link. I want to call reset when page scrolls back to top.

**Comment by jlmakes** [comment]
You can call `sr.sync()` to re-run all `reveal()` calls.

**Comment by jlmakes** [comment]
You can call `sr.sync()` to re-run all `reveal()` calls.

Calling `sync` inside your "back to top" button click handler/callback should get you what you want.

**Comment by dariodev** [comment]
hmmm does not work for me. Can you suggest anything?

**Comment by jlmakes** [comment]
To be clear, you're trying to reveal the elements once without `options.reset`, and then once the user has scrolled back to the top, you want to re-reveal all the elements so they can scroll down again to see the reveals again?
