### ISSUE TITLE
Trigger animation when elements come into viewport using another script

### ISSUE THREAD

**Issue by mankinchan** [jlmakes/scrollreveal#420]
Hi,

I'm new to web development and design and so far I've found ScrollReveal to be a great addition to my web projects.

I do have a question about having ScrollReveal work with another script, [progressbar.js](https://github.com/kimmobrunfeldt/progressbar.js)

I currently have animated progress bars reveal on scroll using ScrollReveal; however, the animation on the progress bar is already done by the time I scroll to that section of the page.

I would like to have the progress bar animation run on scroll and not on page load. 
(and I'm not the only one https://github.com/kimmobrunfeldt/progressbar.js/issues/177)

Can I use ScrollReveal make the animation from progressbar.js wait until the elements are in the viewport? Currently I have it like this:

```html
<script>
	window.sr = ScrollReveal();
	sr.reveal('#ps', {
		container:'.about-history',
		duration: 2000,
		origin:'bottom',
		reset: false,
		useDelay:'always',
		viewFactor: 0.3
	});
</script>
<script>
  	$('#ps').LineProgressbar({
		duration: 11000,
		percentage:90,
		height: '20px',
		width: '98%',
		backgroundColor: '#2c3e50',
		fillBackgroundColor: '#fff'
	});
</script>
```

Thank you in advance.

**Comment by jlmakes** [comment]
ScrollReveal mainly does two things: generate animation styles, and apply them at the right time.

To accomplish the latter, ScrollReveal _does_ check whether elements are visible within the `options.container` (which by default is the window), but it's a relatively small part of the magic.

If all you're looking for is element visibility checking, there are certainly more lightweight solutions available than using ScrollReveal—_that said_, I don't mind showing you something you can try with it.

ScrollReveal also has four callback functions which are invoked at different times during animation:

- `options.beforeReveal`
- `options.beforeReset`
- `options.afterReveal` <— _we'll use this one_
- `options.afterReset`

The general idea is to assign a function to `options.afterReveal` that contains all the code you want to run _after_ your element completes its reveal animation.

> _Allow me to emphasize this point... NOT when it becomes visible, but when it completes its animation after becoming visible. If you want the `afterReveal` callback to fire the instant something is visible, you need an animation with duration (and view factor) of 0._

I have added a demonstration to your code snippet:

```js
window.sr = ScrollReveal();
sr.reveal('#ps', {
	container:'.about-history',
	duration: 2000,
	origin:'bottom',
	reset: false,
	useDelay:'always',
	viewFactor: 0.3,

	// this part is new!
	afterReveal: function(el) {
		console.log(el);
	}
});
```

Also I want to point out that this function is passed the revealed element as `el` by ScrollReveal, so you have easy access to it within that function scope. In my example, I am simply logging it to the console.

It's up to you to figure out what to put in this function (in regards to integrating with progressbar.js), but hopefully this moves you closer to your desired outcome.

Good luck!

**Comment by mankinchan** [comment]
Thank you, this really helped a lot.
