### ISSUE TITLE
Webpage displays for a split second before animations start

### ISSUE THREAD

**Issue by almatrass** [jlmakes/scrollreveal#421]
- Windows 10
- Google Chrome (latest version)
- ScrollReveal v3.4.0

As the title says the page flashes up for a split second before starting the animations, any way to stop this happening?

**Comment by jlmakes** [comment]
I believe what you're describing is known behavior, due to your DOM rendering before JavaScript has evaluated. Check out #411 for a little more.

**Comment by almatrass** [comment]
Thanks a lot
