### ISSUE TITLE
Why is my element not revealing on page load?

### ISSUE THREAD

**Issue by CallumBrankin** [jlmakes/scrollreveal#423]
- Windows 10
- Opera 51.0.2830.55 
- ScrollReveal version 3.3.6

When a large element is within the view factor percentage on page load, ScrollReveal will not trigger the reveal animation on that element. 

```js
(function($) {
$(function() {
    window.sr = ScrollReveal({ reset: false });
    sr.reveal('section > *', {
        delay: 100,
        origin: 'bottom',
        distance: '80px',
        duration: 600,
        delay: 0,
        viewFactor: 0.06,
        easing: 'cubic-bezier(.21,.01,.38,1.15)',
        scale: 1.1
    });
});
})(jQuery);
```

The section element in question is 1841px in width and 3090px in height in desktop view. 311px width and 7868px height in mobile view (iPhone 7).

**Comment by jlmakes** [comment]
Do you mind creating a [JSBin](http://jsbin.com) demo? It would better help me understand and help solve your problem.

**Comment by CallumBrankin** [comment]
@jlmakes I'll attempt to recreate it in JSBin

**Comment by CallumBrankin** [comment]
@jlmakes I've used codepen instead.

Make sure you make the output window as big as possible.

Viewfactor set to default value of 0.2: https://codepen.io/CallumBrankin/pen/oqZggV. The main body of text animates as intended but you need to scroll the page down.

Viewfactor set to 0.06: https://codepen.io/CallumBrankin/pen/JLWodw. The main body of text is visible but doesn't animate in on page load.

**Comment by jlmakes** [comment]
So you're trying to have the body text reveal immediately on page load?

**Comment by jlmakes** [comment]
Callum,

I'd like to first review what `options.viewFactor` actually does. Imagine we are scrolling down, and an element on our page is quickly moving upwards.

<img width="135" src="https://user-images.githubusercontent.com/2044842/37691252-ae22a24a-2c6d-11e8-9749-499a7fac4e60.png">

If we have `options.viewFactor = 0` (which is the default in version 4), the top edge of the element is represented faithfully to its dimensions:

<img width="134" src="https://user-images.githubusercontent.com/2044842/37691326-49f797de-2c6e-11e8-88de-9e293ef3777b.png">
 
This top edge is what ScrollReveal looks for, when checking if an element has crossed the viewport's bottom boundary—and when it does, the element is considered visible and animations are triggered.

This would be the moment our element is considered visible:

<img width="268" src="https://user-images.githubusercontent.com/2044842/37691381-c538555a-2c6e-11e8-9f72-e60e1e86c478.png">

Now, if we were to use `options.viewFactor = 0.2` instead, our element's top edge would be moved inwards 20%:

<img width="323" src="https://user-images.githubusercontent.com/2044842/37691427-2cf17ee2-2c6f-11e8-9ef8-f11a2171b6c3.png">

This adjustment doesn't change the rendered appearance of the element, only where ScrollReveal sees the top edge. So in this case, this would be the moment our element is considered visible:

<img width="263" src="https://user-images.githubusercontent.com/2044842/37691533-e2ba7a76-2c6f-11e8-9431-7255c0a970d6.png">

This behavior applies to all four edges:

* Element's top edge compared to the viewport's bottom boundary.
* Element's right edge compared to the viewport's left boundary.
* Element's bottom edge compared to the viewport's top boundary.
* Element's left edge compared to the viewport's right boundary.

We can generalize `options.viewFactor` as the amount of the element required to be visible, before ScrollReveal will trigger its animations.

**Comment by jlmakes** [comment]
With that said, let's touch on a few things related to your project:

You're using ScrollReveal on a really really really tall element, and `options.viewFactor = 0.06` means that 6% of its height must be past the bottom boundary before it's revealed—which on my screen, meant I had to scroll.

> "The main body of text is visible but doesn't animate in on page load."

**I would recommend `options.viewFactor = 0`**.

Also, I noticed...

The `div.panel.panel-narrow` that you're revealing (which contains your really really tall content), also has a blanket CSS transition applied to it:

```css
.page .panel {
    transition: all .3s ease-in-out;
}
```

I obviously have no idea what this is for in your project, but in this situation it is conflicting with ScrollReveal's CSS transitions—and preventing the initial animation from playing.

**Comment by CallumBrankin** [comment]
@jlmakes Thanks for the clarification!
