### ISSUE TITLE
Only works in chrome?

### ISSUE THREAD

**Issue by KevinAllen4325** [jlmakes/scrollreveal#425]
Testing this in other browsers, it only seems to be working in chrome for both desktop and mobile. If i use any other browser, it doesnt load the sections so they're just left blank. I tried the CDN as well as downloading the files, and removing other libraries but it seems to be an issue with SR itself. Im using a windows 10 machine as well as a galaxy s8

**Comment by jlmakes** [comment]
What version of ScrollReveal?

I automate as much cross-browser testing as possible, but also habitually test across devices manually; my devices on hand are running Firefox and Safari, and both function normally...

I'm not sure what's going on for you, but if you provide a demo I don't mind helping you debug.

**Comment by KevinAllen4325** [comment]
Here's what i'm working on, https://kevinallen4325.github.io/decentralize/

I've tried removing the other libraries to see if something was interfering but nothing changed

**Comment by jlmakes** [comment]
Without a demo created with [JSBin](http://jsbin) or [Codepen](https://codepen.io), I can't do much more than inspect your page. Either way, thanks for providing more information. (I see you're running ScrollReveal v3.4)

This sounds a lot like https://github.com/jlmakes/scrollreveal/issues/379#issuecomment-334201433

> This causes `window.pageYOffset` and `document.documentElement.scrollTop` to always return `0`.

I can confirm these bugged values are the root of the problem; scroll the page and try typing `window.pageYOffset` into your Chrome console, versus the Firefox console. I would recommend exploring the solutions outlined in that issue.

**Comment by KevinAllen4325** [comment]
Ill read through that thread and see if anything helps. If it does, i'll report back here

**Comment by KevinAllen4325** [comment]
So i removed overflow-x:hidden on my body, and that cleared it up. Not sure why that is, but if it works, it works.
