### ISSUE TITLE
Can't get this working on Vue

### ISSUE THREAD

**Issue by nnagewad** [jlmakes/scrollreveal#427]
How do you install this in Vue?

```js
import ScrollReveal from 'scrollreveal'

Vue.use(ScrollReveal)
```
After that it gets borked

Thanks!

> macOS
> Firefox 59
> ScrollReveal 3.4.0

**Comment by jlmakes** [comment]
ScrollReveal is not a [Vue plugin](https://vuejs.org/v2/guide/plugins.html)

> A Vue.js plugin should expose an install method. The method will be called with the Vue constructor as the first argument, along with possible options.

ScrollReveal is a standalone library, that does not implement the Vue plugin interface ; passing the ScrollReveal constructor to `Vue.use()` won't have the desired outcome.

I recommend exploring something like [`vue-scroll-reveal`](https://github.com/tserkov/vue-scroll-reveal).

**Comment by jlmakes** [comment]
Also when using the standalone library, be careful using `import` with ScrollReveal 3.x.

Invoking the constructor in different modules will instantiate multiple copies, which leads to a lot of pain. You can get around this by creating your own wrapper:

_Make a new file `sr.js`_

```js
import ScrollReveal from 'scrollreveal';

export default ScrollReveal();
```

Now when we import the wrapper, we are only ever working with one instance of ScrollReveal.

<details>
<summary>Example</summary>
```js
// a.js
import sr from './sr';

sr.reveal('.some-a-things');
```

```js
// b.js
import sr from './sr';

sr.reveal('.some-b-things');
```
</details>

&nbsp;

> **Note:** This work around is not required for ScrollReveal 4.x.
> (The 4.x constructor _always_ returns the same instance!)

**Comment by eybarta** [comment]
maybe you're looking for this?

[https://github.com/tserkov/vue-scroll-reveal](https://github.com/tserkov/vue-scroll-reveal)
