### ISSUE TITLE
documentation question

### ISSUE THREAD

**Issue by robbisy** [jlmakes/scrollreveal#428]
Julian does data-sr also works with scrollreveal v3.x ?
https://github.com/jlmakes/scrollreveal/wiki/Keywords#note-this-is-legacy-v2x-documentation

**Comment by jlmakes** [comment]
No, all versions 3.x and later use a JavaScript API. (See #194)

The "natural language" inline API used in 2.x and earlier does have some unique strengths, but it was ultimately abandoned as the functionality of ScrollReveal grew.
