### ISSUE TITLE
only one element got trigger for reveal

### ISSUE THREAD

**Issue by marklai1998** [jlmakes/scrollreveal#433]
First I wanna thanks for the fantastic library.

I'm using React with this library right now
But I got trouble when I want to set up more reveal elements

Here is part of my code

```js
componentDidMount() {
    const config = {
        origin: 'top',
        duration: 1000,
        delay: 150,
        distance: '300px',
        opacity: 0,
        easing: 'ease',
        reset: true
    };
    const config_player = {
        origin: 'left',
        duration: 1000,
        delay: 150,
        distance: '300px',
        opacity: 0,
        easing: 'ease',
        reset: true
    };
    ScrollReveal().reveal(this.refs.player, config_player);
    ScrollReveal().reveal(this.refs.abouttitle, config);
}
```

with two DOM elements, they act weirdly
Only one reveal correctly. Other one did noting(the style didn't trigger at all)

I'm also a newbie to React, perhaps I did something wrong.

**Comment by marklai1998** [comment]
Tried with class
 ScrollReveal().reveal(".player", config_player);
still not work

Part of my DOM

`<div className="container">`
`                       <div className="row justify-content-around">`
`                            <div className="col-8 col-sm-8 col-md-4 col-lg-4 col-xl-4">`
`                                <img src={player} className="player" alt="player" ref='player'/>`
`                            </div>`
`                            <div className="col-10 col-sm-12 col-md-8 col-lg-6 col-xl-5">`
`                                <h1 ref='abouttitle'>About Us</h1><br/>`
`                            </div>`
`                        </div>`

**Comment by jlmakes** [comment]
What version of ScrollReveal are you using?

**Comment by marklai1998** [comment]
Tried the latest. and the 4.0 beta

**Comment by jlmakes** [comment]
Well this snippet of code...

```js
ScrollReveal().reveal(this.refs.player, config_player);
ScrollReveal().reveal(this.refs.abouttitle, config);
```

...will not work with ScrollReveal 3.x, because invoking `ScrollReveal()` will return a new instance each time. (Multiple instances have never been supported, but 4.x is the first version to enforce the singleton pattern.)

```js
// 3.x
ScrollReveal() === ScrollReveal() // false

// 4.x
ScrollReveal() === ScrollReveal() // true
```

For this reason, if you're using ScrollReveal in a modular development environment, you either want to use 4.x or [create your own 3.x singleton](https://github.com/jlmakes/scrollreveal/issues/427#issuecomment-381311272).

**Comment by marklai1998** [comment]
Just reload my project and it works 
I think the 4.x beta need a refresh of the project for it to work
Thx
