### ISSUE TITLE
pixel-based viewFactor

### ISSUE THREAD

**Issue by dolanb12** [jlmakes/scrollreveal#435]
I'd love to be able to have a pixel-based viewFactor option. 

When I enable for mobile, having sections that have dynamic height (because of changing viewport width) -- I run into an issue because a 50% viewFactor means something very different when a mobile phone's width has made the section's height much larger, sometimes larger than the vh itself.

If I were to animate single html elements, this wouldn't be as big of an issue, but I'd really like to reveal full sections.

Any suggestions?

Thanks!

**Comment by jlmakes** [comment]
Hey @dolanb12,

So you've been using `options.viewFactor` to change the "active boundaries" of elements, defined as a percentage.

Well you can also use `options.viewOffset` to change the "active boundaries" of the viewport, defined in pixels (for each direction).

_Example_:

```js
var sr = ScrollReveal();
var options = {
  viewOffset: {
    top: 75,
    bottom: 75
  }
};

sr.reveal('.items', options);
```

> See [The Starting Defaults](https://github.com/jlmakes/scrollreveal#22-the-starting-defaults) for more information.

Good luck!

**Comment by dolanb12** [comment]
Thanks for this! I should be able to accomplish what I need with a little experimenting. Cheers!
