### ISSUE TITLE
scrollrevealjs not working on IE11

### ISSUE THREAD

**Issue by fengitel** [jlmakes/scrollreveal#436]
Hi,
I can't manage to get scrollrevealjs working on InternetExplorer 11. Animations doesn't start at all.
Even on the demo page (https://scrollrevealjs.org/) I get a black screen (no colored bars at all).
JS is enabled.
It's there something I'm missing?

Regards
F.

**Comment by jlmakes** [comment]
ScrollReveal works on browsers that support both CSS Transition and Transform (which includes IE10+), but you're right [there is a problem with the demo](222): I used the newer view units `vw` and `vh` for the color bars, which _do not_ play nicely with CSS Transforms in IE.

[Here's a ScrollReveal demo](https://jsbin.com/totumop/edit?html,output) (without view units) you can test.
