### ISSUE TITLE
Hello, how do I destroy it?

### ISSUE THREAD

**Issue by silence1996** [jlmakes/scrollreveal#438]
Hello, how do I destroy it? My page has a hidden and displayed button. The hidden button can hide the container that uses this js. When I press the display button, I want to display this container and perform an animation.

Using ScrollReveal v3.4.0.

**Comment by jlmakes** [comment]
What version of ScrollReveal are you using?

**Comment by silence1996** [comment]
Thank you for your reply, using your latest version, v3.4.0

**Comment by jlmakes** [comment]
ScrollReveal v3.x isn't well suited for manually controlling animations. That said, I'm not sure I understand what you're trying to build. If you'd like, you can show me what you've tried.
