### ISSUE TITLE
V4 issue in isElementVisible when using Turbolinks

### ISSUE THREAD

**Issue by dylanfisher** [jlmakes/scrollreveal#440]
I'm working on a site using Turbolinks 5 in Rails and the V4 branch of scrollreveal. I noticed when navigating quickly back and forth between pages these errors would crop up.

`Uncaught TypeError: Cannot read property 'bounds' of undefined`
`Uncaught TypeError: Cannot read property 'geometry' of undefined`

Updating the `isElementVisible` to check for the presence of these elements seems to have fixed the problem:

```js
function isElementVisible(element) {
  if ( !element ) return;
  var container = this.store.containers[element.containerId];
  if ( !container ) return;
```

**Comment by ekfuhrmann** [comment]
One of the default properties you can set is `useDelay`, which has an option of `onload`. This may save you from needing to run that `isElementVisible` function.


Example:
```js
// useDelay options:
// 'always' — delay for all reveal animations
// 'once'   — delay only the first time reveals occur
// 'onload' - delay only for animations triggered by first load

sr.reveal('.foo', { useDelay: 'onload' });
```

**Comment by dylanfisher** [comment]
Didn't seem to help. Perhaps it's because of the way I'm using the `destroy` function? My whole initialization looks like this:

```
App.sr = ScrollReveal();

$(document).on('turbolinks:load', function() {
  App.sr.reveal('.block', {
    duration: 1000,
    scale: 1,
    distance: '60px',
    easing: 'ease'
  });

  $(document).one('turbolinks:before-cache', function() {
    App.sr.destroy();
  });
});
```

**Comment by jlmakes** [comment]
Hey Dylan, thanks for raising an issue with a proposed solution!

I've actually seen this error before (#349), which I believe is caused by calling `clean()` or `destroy()` during the event handler; the list of elements is removed from the store, so `isElementVisible()` begins receiving `undefined`.

I'll give this some attention this week, and make sure a solution goes into the next release.

**Comment by jlmakes** [comment]
Hey Dylan, thanks for raising an issue with a proposed solution!

I've actually seen this error before (#349):

> From my tinkering, it seems the ScrollReveal store is being nuked by `clean()` or `destroy()` midway through looping over elements, so `isElementVisible()` attempts to access `element` and `container` data that no longer exists.

I'll give this some attention this week, and make sure a solution goes into the next release.

**Comment by jlmakes** [comment]
If you don't mind @danielkorte, give `beta.32` a try to see if it fixes your issue.

**Comment by jlmakes** [comment]
If you don't mind @dylanfisher, give `beta.32` a try to see if it fixes your issue.

**Comment by dylanfisher** [comment]
Hey that's great Julian, I just tested and don't see the errors. 👍
