### ISSUE TITLE
The external java script file is not working in angular js app

### ISSUE THREAD

**Issue by MughilanKarthick** [jlmakes/scrollreveal#441]
The app.js file is working in the localhost only and also working only after the refresh of page.

There is no error shown in console.

**Comment by jlmakes** [comment]
Sounds like an issue with how your project is setup. If you show me how you're using ScrollReveal, I may have some insight to offer.

**Comment by MughilanKarthick** [comment]
i have a problem on linking the external java script libraries to my
angular application. The libraries make changes in html file only after
refreshing the page
