### ISSUE TITLE
afterReveal doesn't fire in time (Chrome, SR beta)

### ISSUE THREAD

**Issue by ugrupp** [jlmakes/scrollreveal#442]
- OS: OSX
- Browser: Chrome only, Firefox and Safari seem to be fine
- SR version: 4.0.0-beta.32

Hey, loving the script, thanks! I'm using the beta so I can get the nice sequencer animations.

One problem though: On Chrome, the sequence sometimes gets stuck in the middle, leaving the screen half-empty for several seconds. It doesn't seem to happen on other browsers.
I activated the callbacks and I noticed that `afterReveal` fires way too late. When it finally fires, the sequence continues. In other words, the time between `beforeReveal` and its corresponding `afterReveal` sometimes is way longer that the specified `duration`.

Here's a gif illustrating the problem:
![sequencebug2](https://user-images.githubusercontent.com/3763431/41970067-bdbf0b6e-7a09-11e8-9bbc-d84c1e943182.gif)

Thanks for looking into it!

Config:
```js
{
    duration: 750,
    delay: 0,
    distance: '3rem',
    scale: 1,
    interval: 100,
    viewFactor: 0.1,
    useDelay: 'onload',

    // Demo/debug callbacks
    beforeReveal: function (domEl) {
      console.log('beforeReveal', domEl);
    },
    beforeReset: function (domEl) {
      console.log('beforeReset', domEl);
    },
    // Callbacks that fire for each completed element reveal, and reset.
    afterReveal: function (domEl) {
      console.log('afterReveal', domEl);
    },
    afterReset: function (domEl) {
      console.log('afterReset', domEl);
    }
  }
```

**Comment by ugrupp** [comment]
I managed to narrow it down to the `setTimeout` call in the `cue` function. For some reason, it behaves like it's running in a background tab, as described here: https://stackoverflow.com/questions/5927284/how-can-i-make-setinterval-also-work-when-a-tab-is-inactive-in-chrome

One of the solutions there is to defer setTimeout calls into WebWorkers, having them executed inside a different Thread. There's a library for that, taking quite a radical approach, deferring _all_ timeouts into a WebWorker: https://github.com/turuslan/HackTimer

Including the library worked for me, the sequences now run without getting stuck.

Perhaps, this functionality could be integrated into SR itself?

**Comment by jlmakes** [comment]
Hey @ugrupp, thanks for all the info!

Getting the sequences to behave intuitively has been a real pain, but I haven't encountered the bug you describe where the sequence stalls for moment before continuing. Do you think you could recreate it in an isolated fashion?

I wonder if there are other Chrome Developer Tools that could help us identify why the "throttling" would occur (if you're not burying the tab).

**Comment by evromalarkey** [comment]
I am having this issue on older version Safari 10.1.2, but it works in latest version and any other browser, so nothing breaking. (sr version 4.0.4)
