### ISSUE TITLE
ScrollReview viewFactor only works from bottom to top of the page.

### ISSUE THREAD

**Issue by jovvybersamin** [jlmakes/scrollreveal#443]
Here is my implementation.

```js
window.sr = ScrollReveal({ reset: true });

sr.reveal('.services-title', {
    duration: 2000,
    origin: 'top',
    viewFactor: 0.2
});

sr.reveal('.mission-vision-title', {
    duration: 2000,
    origin: 'top',
    viewFactor: 0.2
});
```

Anyone knows why?

**Comment by jlmakes** [comment]
Have you had any luck recreating this problem with something like [JSBin](http://jsbin)?

**Comment by jlmakes** [comment]
I'm not sure how to help. Can you demonstrate the problem?

For what it's worth, here's a [demo](http://jsbin.com/zoxoquxiya/edit?html,output) showing `options.viewFactor` using ScrollReveal 3.

**Comment by jlmakes** [comment]
Nothing suspicious stands out about the JavaScript you shared. I'm not sure how to help with more information about your project. Better yet, can you demonstrate the problem?

> Also, for what it's worth, here's a [demo](http://jsbin.com/zoxoquxiya/edit?html,output) of correct `options.viewFactor` behavior using ScrollReveal 3.

**Comment by JohnPhilosopher** [comment]
One thing you could try is in your css is doing
`html, body 
{
height: 100%;
}
 `

**Comment by jovvybersamin** [comment]
@JohnPhilosopher thanks mate, I'll try that.

**Comment by jovvybersamin** [comment]
html, body { height: 100%; }

This fixes the issue.
