### ISSUE TITLE
How to use scrollReveal. Js in angular6

### ISSUE THREAD

**Issue by leoshuaige** [jlmakes/scrollreveal#444]
How to use scrollReveal. Js in angular6

Thanks!

**Comment by jlmakes** [comment]
I did a quick Google search and found [how to use external libraries with Angular](https://github.com/angular/angular-cli/wiki/stories-third-party-lib):

- `npm i scrollreveal@beta --save`
- create/open `src/typings.d.ts` and add `declare module 'scrollreveal';`
- In your component `import * as ScrollReveal from 'scrollreveal'`

Good luck!
