### ISSUE TITLE
Using ScrollReveal with Laravel?

### ISSUE THREAD

**Issue by D4RKAR117** [jlmakes/scrollreveal#447]
- Ubuntu 18.04 LTS
- Firefox Quantum v61.0.1 And Opera 54.0.2952
- Scrollreveal v3.4.0 (First Usage try), Now Beta 4.0-beta32

I'm trying to use ScrollReveal v3.4.0 in my Laravel web page, but the animations never start, later I install v4.0.0-beta.32 hoping that will help me, but the animations never start. Idk if im doing anything wrong but I cant find any example of usage with Laravel 

![imagen](https://user-images.githubusercontent.com/23545823/42985876-e0d8d132-8bb8-11e8-9b32-eeab9a0cdf99.png)

that its my custom script, i follow all available documentation.

![imagen](https://user-images.githubusercontent.com/23545823/42986208-50bf699c-8bba-11e8-89f1-7db3796f53bc.png)
Here its my custom class implementation for reveals.

![imagen](https://user-images.githubusercontent.com/23545823/42985933-2037f6e6-8bb9-11e8-9068-a676ad1d6fb0.png)
and that its my laravel blade page with the CDN (I try importing sr.js and sr.min.js local scripts that can be seen in the previous screenshot, but it always gives the same result and the animations do not start,)

 I would appreciate a guide or how to use scrollreveal with laravel, including its implementations of webpack.

Thanks, Ill waiting for your answer!

**Comment by jlmakes** [comment]
I'm not familiar with Laravel, or how it works with 3rd party libraries/dependencies.
Are there any errors in the console?

**Comment by D4RKAR117** [comment]
527/5000
Thanks for responding quickly.
first I want to confirm that laravel effectively uses npm as dependencies manager, as explained in this [**link**](https://laravel.com/docs/5.6/mix), mix imports of external JS libraries should go in the file /resources/assets/js/app.js, so that later webpack compile and minify the code inside the deployment folder public/js/app.js.

Try what you suggested earlier by applying your response and the laravel documentation for the use of external JS libraries as follows:

![imagen](https://user-images.githubusercontent.com/23545823/43004642-052fbb8a-8bf6-11e8-8680-fa53fbac972f.png)
This is my assets app.js file and as you suggested try adding:
 `const ScrollReveal = require("scrollreveal");` into the file. 

![imagen](https://user-images.githubusercontent.com/23545823/43004893-bb5f880e-8bf6-11e8-89e4-8054636c78fb.png)
This is my custom script where I applied the other part of your suggestion

![imagen](https://user-images.githubusercontent.com/23545823/43005290-0e28dde6-8bf8-11e8-80ca-885daaa57574.png)
and finally, again here is my view where to use both my custom script and the deployment app.js (Remember that in theory when you import a library inside the asset app.js, deployment app.js works like the script of the imported JS library).

I removed the CDN from the view, later in the display of my page look for errors in the console as you suggested.

![imagen](https://user-images.githubusercontent.com/23545823/43005553-d686e4e0-8bf8-11e8-8e7c-795aa4f54ee2.png)


I removed the CDN from the view, later in the display of my page look for errors in the console as you suggested, but this error is new, it did not appear when I tried to use the CDN or the local script: sr.js / sr.min.js

I appreciate your help enormously, I hope you can help me with this problem, and that this could be a contribution for future versions of this incredible javascript library.

**Comment by jlmakes** [comment]
ScrollReveal is not defined when/where you're trying to use it.

Notice how for Vue, you are assigning to the global object, e.g:

```js
// app.js
window.Vue = require('vue');
```

This makes `Vue` a global variable. I would guess you either need to do the same for ScrollReveal, e.g:

```js
// app.js
window.ScrollReveal = require('scrollreveal');
```

Or, as I showed you, require `scrollreveal` _in the same file_ where you intend to use it, e.g:

```js
// webAni.js

const ScrollReveal = require("scrollreveal");

ScrollReveal().reveal('.top-reveal', { ... });
ScrollReveal().reveal('.right-reveal', { ... });
```

**Comment by jlmakes** [comment]
ScrollReveal is not defined when/where you're trying to use it.

Notice how for Vue, you are assigning to the global object, e.g:

```js
// app.js
window.Vue = require('vue');
```

This makes `Vue` a global variable. I would guess you either need to do the same for ScrollReveal, e.g:

```js
// app.js
window.ScrollReveal = require('scrollreveal');
```

...OR require `scrollreveal` _in the same file_ where you intend to use it, e.g:

```js
// webAni.js
const ScrollReveal = require("scrollreveal");

ScrollReveal().reveal('.top-reveal', { ... });
ScrollReveal().reveal('.right-reveal', { ... });
```

**Comment by D4RKAR117** [comment]
ok I just tried your new suggestions as follows:
![imagen](https://user-images.githubusercontent.com/23545823/43021611-defbee28-8c29-11e8-9c3e-5c93a1e342f2.png)

this is my `resources/assets/js/app.js` i added the 

> window.ScrollReveal = require('scrollreveal'); first without any another modification, it doesnt work and the console still trows the  undefined error.
After that i tried add the laravel defualt format to package as shown in the previous screenshot with the `require('../../../node_modules/scrollreveal');`, it doest affect in anything.

last i tried add to the `public/js/webAni.js` the line `const ScrollReveal = require("scrollreveal");` and then this happen in the console.

![imagen](https://user-images.githubusercontent.com/23545823/43022041-763298e0-8c2b-11e8-84e0-4840093a5bd0.png)

another kind of error.

But trying to validate the code using the visual studio code, I found the following regarding the scrollreveal package.


![imagen](https://user-images.githubusercontent.com/23545823/43022400-c7341a06-8c2c-11e8-82d1-cc701392ade7.png)

The translation of the mensage says: 

```
No declaration file was found for the 'scrollreveal' module. '/home/d4rkar117/GitRepos/DatacenterWeb/node_modules/scrollreveal/dist/scrollreveal.js' has an implicit "any" type.
   Try "npm install @ types / scrollreveal" if it exists or add a new declaration file (.d.ts) that includes "declare module 'scrollreveal';"
```
that note appears with or without `require('../../../node_modules/scrollreveal');`, idk if this message has any kind of relevance in this case but ill wait for your coments.

**Comment by jlmakes** [comment]
You should not be responsible for locating node package file paths, e.g:

```js
require('../../../node_modules/scrollreveal');
```

you should only need to pass the package name, e.g:

```js
require('scrollreveal');
```

From the `ReferenceError: require is not defined` inside `webAni.js`, it’s clear that you should only be using `require()` inside of `app.js`, so I still believe that this is correct:

```js
// app.js
window.ScrollReveal = require('scrollreveal');
```

Also this...

> No declaration file was found for the 'scrollreveal' module...
> Try `npm install @types/scrollreveal` if it exists or add a new declaration file (.d.ts) that includes `declare module 'scrollreveal';`

I don’t think the missing type definitions error message matters, unless you’re using TypeScript.

***

If you’re getting `ReferenceError: ScrollReveal is undefined` from your `webAni.js` script, I would guess it’s the order in which your scripts are loaded/executed.

I don‘t know what else to suggest.

This doesn’t appear to be a ScrollReveal problem, but a question of how to get 3rd party scripts working with Laravel. There must be more Laravel documentation, or a community forum, that can better help you with this.

**Comment by jlmakes** [comment]
You should not be responsible for locating node package file paths, e.g:

```js
require('../../../node_modules/scrollreveal');
```

you should only need to pass the package name, e.g:

```js
require('scrollreveal');
```

From the `ReferenceError: require is not defined` inside `webAni.js`, it’s clear that you should only be using `require()` inside of `app.js`, so I still believe that this is correct:

```js
// app.js
window.ScrollReveal = require('scrollreveal');
```

Also this...

> No declaration file was found for the 'scrollreveal' module...
> Try `npm install @types/scrollreveal` if it exists or add a new declaration file (.d.ts) that includes `declare module 'scrollreveal';`

I don’t think the missing type definitions error message matters, unless you’re using TypeScript.

***

If you’re getting `ReferenceError: ScrollReveal is undefined` from your `webAni.js` script, I would guess it’s the order in which your scripts are loaded/executed. This doesn’t appear to be a ScrollReveal problem, but a question of how to get 3rd party scripts working with Laravel. 

I did notice however, that you’re using the `defer` attribute on your `app.js` script tag.

> **defer**
>
> This Boolean attribute is set to indicate to a browser that the script is meant to be executed after the document has been parsed, but before firing `DOMContentLoaded`. Scripts with the defer attribute will prevent the `DOMContentLoaded` event from firing until the script has loaded and finished evaluating.
>
> — [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script)

I'm not sure, but this could be why your `webAni.js` may be evaluated before the `app.js` has had a chance to execute. Sounds like you want to wait for the `DOMContentLoaded` event before attempting to use ScrollReveal (or any of your 3rd party scripts).

I would recommend checking with the Laravel community on script execution order, or exploring the use of [`DOMContentLoaded` event listeners](https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded) inside your `webAni.js` file.

**Comment by jlmakes** [comment]
You should not be responsible for locating node package file paths, e.g:

```js
require('../../../node_modules/scrollreveal');
```

you should only need to pass the package name, e.g:

```js
require('scrollreveal');
```

From the `ReferenceError: require is not defined` inside `webAni.js`, it’s clear that you should only be using `require()` inside of `app.js`, so I still believe that this is correct:

```js
// app.js
window.ScrollReveal = require('scrollreveal');
```

Also this...

> No declaration file was found for the 'scrollreveal' module...
> Try `npm install @types/scrollreveal` if it exists or add a new declaration file (.d.ts) that includes `declare module 'scrollreveal';`

I don’t think the missing type definitions error message matters, unless you’re using TypeScript.

***

If you’re getting `ReferenceError: ScrollReveal is not defined` from your `webAni.js` script, I would guess it’s the order in which your scripts are loaded/executed. This doesn’t appear to be a ScrollReveal problem, but a question of how to get 3rd party scripts working with Laravel. 

I did notice however, that you’re using the `defer` attribute on your `app.js` script tag.

> **defer**
>
> This Boolean attribute is set to indicate to a browser that the script is meant to be executed after the document has been parsed, but before firing `DOMContentLoaded`. Scripts with the defer attribute will prevent the `DOMContentLoaded` event from firing until the script has loaded and finished evaluating.
>
> — [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script)

I'm not sure, but this could be why your `webAni.js` may be evaluated before the `app.js` has had a chance to execute. Sounds like you want to wait for the `DOMContentLoaded` event before attempting to use ScrollReveal (or any of your 3rd party scripts).

I would recommend checking with the Laravel community on script execution order, or exploring the use of [`DOMContentLoaded` event listeners](https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded) inside your `webAni.js` file.

**Comment by D4RKAR117** [comment]
Ok, finally after hours experimenting and thanks to your last suggestion, I successfully managed to set up your wonderful library. I will explain how I did it with the hope that you add this to your documentation and the clarification of my final doubt, after this you can terminate this issue.

First, the defer attribute in the <script> tag of my view was blocking the loading of your library, so I had to resort to creating my own external compilation file for laravel elixir and webpack called customlibs.js located in my assets folder, which contains the following code.

![imagen](https://user-images.githubusercontent.com/23545823/43030702-babf932c-8c59-11e8-80df-5df63a6a421a.png)

The next thing I did, was guiding myself by the laravel documentation found in this [**link**](https://laravel.com/docs/5.4/mix#working-with-scripts). Modify my webpack.mix.js file by adding the configuration of my customlibs.js file ("located in my assets folder") as follows.

![imagen](https://user-images.githubusercontent.com/23545823/43030741-4fe371ee-8c5a-11e8-8c6d-bfea53e2fb68.png)

This defines how the library is processed for the rest of the webpack including its global name and the export of minified library file to public/js/sr.min.js. As a final step, modify my webAni.js script with the DOM waiting parameters, as you indicated in the previous suggestion, for which the file is written in the following way.

![imagen](https://user-images.githubusercontent.com/23545823/43030812-6de390e2-8c5b-11e8-9135-4e822f5ae472.png)

Here is where I made my final question, how can I apply the attributes of reset: true and delay: "onload", to load the animations ("That are already working without problem").

Finally in my view I just had to add the corresponding generated files in my public / js / folder, this includes the minified file of the javascript library as follows.

![imagen](https://user-images.githubusercontent.com/23545823/43030862-3801deb0-8c5c-11e8-81e4-2f950290ba3e.png)

I want to thank you for your time and your immense help, I hope you can add this to some section of the documentation, so that it will be useful for other users in the future. I hope you continue to maintain this incurable library.

Thank you, I await your answer to my last question, after that you can mark the issue as closed.

**Comment by jlmakes** [comment]
Thanks for the kind words @D4RKAR117, glad things are working.

In `customlibs.js` you have:

```js
require('scrollreveal');

window.ScrollReveal = require('scrollreveal');
```

I believe you should only have to require it once:

```js
window.ScrollReveal = require('scrollreveal');
```

You ask:

> Here is where I made my final question, how can I apply the attributes of `reset: true` and `delay: "onload"` to load the animations?

Your `webAni.js` looks more or less like this:

```js
document.addEventListener('DOMContentLoaded', function (event) {
    ScrollReveal().reveal('.right-reveal', { ... });
    ScrollReveal().reveal('.left-reveal', { ... });
    ScrollReveal().reveal('.top-reveal', { ... });
    ScrollReveal().reveal('.bot-reveal', { ... });
});
```

Adding something like this should work:

```diff
    document.addEventListener('DOMContentLoaded', function (event) {
+
+       ScrollReveal({ reset: true, delay: 'onload' });
+
        ScrollReveal().reveal('.right-reveal', { ... });
        ScrollReveal().reveal('.left-reveal', { ... });
        ScrollReveal().reveal('.top-reveal', { ... });
        ScrollReveal().reveal('.bot-reveal', { ... });
    });
```

In ScrollReveal 4, you can call `ScrollReveal()` pretty much anywhere, safely. So you can pass your custom `options` to either `ScrollReveal(options)` or `reveal(target, options)`

Good luck!

**Comment by jlmakes** [comment]
Thanks for the kind words @D4RKAR117, glad things are working.

In `customlibs.js` you have:

```js
require('scrollreveal');

window.ScrollReveal = require('scrollreveal');
```

Maybe it’s something specific to Laravel, but I believe you should only have to require it once:

```js
window.ScrollReveal = require('scrollreveal');
```

You ask:

> Here is where I made my final question, how can I apply the attributes of `reset: true` and `delay: "onload"` to load the animations?

Your `webAni.js` looks more or less like this:

```js
document.addEventListener('DOMContentLoaded', function (event) {
    ScrollReveal().reveal('.right-reveal', { ... });
    ScrollReveal().reveal('.left-reveal', { ... });
    ScrollReveal().reveal('.top-reveal', { ... });
    ScrollReveal().reveal('.bot-reveal', { ... });
});
```

Adding something like this should work:

```diff
    document.addEventListener('DOMContentLoaded', function (event) {
+
+       ScrollReveal({ reset: true, delay: 'onload' });
+
        ScrollReveal().reveal('.right-reveal', { ... });
        ScrollReveal().reveal('.left-reveal', { ... });
        ScrollReveal().reveal('.top-reveal', { ... });
        ScrollReveal().reveal('.bot-reveal', { ... });
    });
```

In ScrollReveal 4, you can call `ScrollReveal()` pretty much anywhere, safely. So you can pass your custom `options` to either `ScrollReveal(options)` or `reveal(target, options)`

Good luck!

**Comment by jlmakes** [comment]
Thanks for the kind words @D4RKAR117, glad things are working.

In `customlibs.js` you have:

```js
require('scrollreveal');

window.ScrollReveal = require('scrollreveal');
```

Maybe it’s something specific to Laravel, but I believe you should only have to require it once:

```js
window.ScrollReveal = require('scrollreveal');
```

You ask:

> Here is where I made my final question, how can I apply the attributes of `reset: true` and `delay: "onload"` to load the animations?

Your `webAni.js` looks more or less like this:

```js
document.addEventListener('DOMContentLoaded', function (event) {
    ScrollReveal().reveal('.right-reveal', { ... });
    ScrollReveal().reveal('.left-reveal', { ... });
    ScrollReveal().reveal('.top-reveal', { ... });
    ScrollReveal().reveal('.bot-reveal', { ... });
});
```

Adding something like this should work:

```diff
    document.addEventListener('DOMContentLoaded', function (event) {
+
+       ScrollReveal({ reset: true, useDelay: 'onload' });
+
        ScrollReveal().reveal('.right-reveal', { ... });
        ScrollReveal().reveal('.left-reveal', { ... });
        ScrollReveal().reveal('.top-reveal', { ... });
        ScrollReveal().reveal('.bot-reveal', { ... });
    });
```

In ScrollReveal 4, you can call `ScrollReveal()` pretty much anywhere, safely. So you can pass your custom `options` to either `ScrollReveal(options)` or `reveal(target, options)`. New website/documentation coming in just a few days!

Good luck!
