### ISSUE TITLE
After reveals, extra blank area is added to right of body

### ISSUE THREAD

**Issue by mikerockett** [jlmakes/scrollreveal#50]
This is quite strange, especially for such an awesome plugin.

I have three boxes that reveal. When they're done, an un-inspectable area appears to the right of the page, enforcing a horizontal scroll bar. I say un-inspectable, because if you try to inspect the area that's been added, it inspects the `<html>` tag instead.

What's even weirder is that this only occurs when I am navigating to and from the page on question. However, if I press `F5` on this page, it doesn't add the empty space.

Here's an image:

![scrollreveal](https://cloud.githubusercontent.com/assets/4586280/2851528/a9bbe63c-d11b-11e3-9162-9fb3eb18d96b.png)

**Note:** This only seems to happen in WebKit (or Blink) browsers. Firefox and IE run everything perfectly — and interestingly enough, [this plugin](http://mynameismatthieu.com/WOW/) (very similar to scrollReveal) does exactly the same thing!

**Comment by ben8jam** [comment]
@jlmakes Thank you!!

**Comment by deepakya** [comment]
But, what if  i add `body {overflow-x: hidden}` then also it fixes the issue for me? but is it a good practice?

**Comment by happy2deepak** [comment]
But, what if i add body {overflow-x: hidden} then also it fixes the issue for me. But is it a good practice?

**Comment by jlmakes** [comment]
@happy2deepak `overflow` or `overflow-x` are a common and perfectly acceptable practice.

>"And still is that javascript work-around needed even after this CSS ?"

No. The JavaScript in the above example was just because I was referencing @unitxt’s example, and I did point this out:

>"It‘s worth mentioning that [this] demo still works without the JavaScript."

**Comment by DanielReyes03** [comment]
Thanks @jlmakes,  `overflow: hidden; `  works for me.
