### ISSUE TITLE
scrollreveal / vue-scroll-reveal Typescript

### ISSUE THREAD

**Issue by HoehensteigerGames** [jlmakes/scrollreveal#509]
HI,

i am trying to use  scrollreveal for vue. I saw in another Issue that there is a vue-scroll-reveal project. I imported the vue-scroll-reveal. My problem is that i am working with Typescript. Is there a Version of scrollreveal or vue-scroll-reveal where i can use @types/vue-scroll-reveal or someting like that. Or is there an d.ts file available? I Hope anyone can help me to use scroll reveal in may vue Project.

Thank you for help.

lg chriss

**Comment by jlmakes** [comment]
There are no typings that I'm aware of for ScrollReveal, or third-party adapters. This will likely be addressed in an upcoming release, but for now it's up to you :)
