### ISSUE TITLE
Cannot find clean method or options in TypeScript

### ISSUE THREAD

**Issue by GiorgioPeng** [jlmakes/scrollreveal#513]
when I use create-react-app and Typescript.
```js
ScrollReveal().reveal("#xx",{ duration: 500,distance: '30px',clean:true})
```
<img width="951" alt="截屏2020-03-26 上午12 32 09" src="https://user-images.githubusercontent.com/34415646/77561104-3bf44e00-6ef9-11ea-84e2-2c05a3bdd270.png">

And it reminds me can not find "clean". And when I checked the Declaration file which is created by ts, I also could not find the "clean" attribute. Can I use it in TypeScript?
<img width="897" alt="截屏2020-03-26 上午12 30 19" src="https://user-images.githubusercontent.com/34415646/77560907-fb94d000-6ef8-11ea-841e-fb95882a49c1.png">

**Comment by jlmakes** [comment]
I believe you're referring to is [`options.cleanup`](https://scrollrevealjs.org/api/cleanup.html)

**Comment by jlmakes** [comment]
I believe you're referring to [`options.cleanup`](https://scrollrevealjs.org/api/cleanup.html), which is an option to control whether or not the [`clean()`](https://scrollrevealjs.org/api/clean.html) method is called automatically after reveals.

**Comment by GiorgioPeng** [comment]
Sorry, I made a mistake. But when I tried to use the options.cleanup, it still reminded me there is something wrong. 
<img width="942" alt="截屏2020-03-26 上午8 20 27" src="https://user-images.githubusercontent.com/34415646/77597894-34ee2f80-6f3b-11ea-9d1d-a6adc9d83bbb.png">

**Comment by GiorgioPeng** [comment]
And I found a mistake in the API documentation.
<img width="773" alt="截屏2020-03-26 上午8 45 25" src="https://user-images.githubusercontent.com/34415646/77598974-3f5df880-6f3e-11ea-84c8-1907898e4609.png">

**Comment by jlmakes** [comment]
Well there aren't first party typings. Where are you getting these types? Specifically, where is the `ScrollRevealObjectOptions` interface defined?

**Comment by jlmakes** [comment]
Well there aren't first party typings. Where are you getting these types? Specifically, where is the `ScrollRevealObjectOptions` interface defined?

**Comment by GiorgioPeng** [comment]
Thank you, I know how to solve the problem now. 
I get it by 
```shell
yarn add @types/scrollreveal
```
[The interface is defined from here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/scrollreveal)
