### ISSUE TITLE
Flyout menus and z-index

### ISSUE THREAD

**Issue by tsangaris** [jlmakes/scrollreveal#515]
### Environment

* Operating System: MacOS 10.15.4
* Browser Version: Chrome 80.0.3987.149 (Official Build) (64-bit)
* ScrollReveal Version: "scrollreveal": "^4.0.6",

Hi,

I am building a website with a Navbar that has Flyout menus (something similar to Stripe.com).

Below the navbar, I have some text that I use ScrollReveal to reveal them. After I reveal them, the flyout menus are hidden behind the text.

If I go to inspect element and disable the:

`transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);`

from the element (text), then the flyout menu is back on top of everything again.

So, to fix this I use the callback function, and I do:

`function myCallback(el) {
        el.style.transform = null;
    }`

Is this the appropriate way to fix this issue? Will this transform disabling affect something else?

Thanks.

**Comment by jlmakes** [comment]
By removing the `transform` property value, you are destroying its [Stacking Context (MDN)](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). If you're looking for alternative solutions, the documentation may give you ideas on how to refactor.

**Comment by jlmakes** [comment]
> Is this the appropriate way to fix this issue? Will this transform disabling affect something else?

As far as ScrollReveal is concerned, I don't think it breaks anything.

By removing the `transform` property value, you are destroying its [Stacking Context (MDN)](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). If you're looking for alternative solutions, the documentation may give you ideas on how to refactor.

**Comment by jlmakes** [comment]
> Will this transform disabling affect something else?

As far as ScrollReveal is concerned, I don't think it breaks anything.

By removing the `transform` property value, you are destroying its [Stacking Context (MDN)](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). If you're looking for alternative solutions, the documentation may give you ideas on how to refactor.
