### ISSUE TITLE
Staggered Reveal

### ISSUE THREAD

**Issue by kerns** [jlmakes/scrollreveal#518]
Just entering this feature request into the record. Staggered reveal would be just like the sequenced reveal but randomized. In many ways this mimics or emulates real-time lazy loading.

**Comment by jlmakes** [comment]
I'm not sure it's exactly what you're imagining, but I was thinking you could randomize the `options.delay` for each revealed item.

```js
let items = [].slice.call(document.querySelectorAll('.item'))

for (let item of items) {
    ScrollReveal().reveal(item, {
      reset: true,
      delay: Math.random() * 1000
    });
}
```

See the [Demo on JSbin](https://jsbin.com/gasuwacece/1/edit?js,output)

**Comment by kerns** [comment]
YES. That's it. Thanks 👍 Hope to see it as a feature in your next release should that come.
