### ISSUE TITLE
How to scale up and down

### ISSUE THREAD

**Issue by lovecoding-git** [jlmakes/scrollreveal#526]
Hi, Thank you for such great package.
My one question is how to apply multi-step scale?

For example I want to put breathing effect. 
scale(1)->scale(1.01) -> scale(0.95)
0s------------0.5s------------1s
How can I do it?

**Comment by jlmakes** [comment]
There's presently no way to define multi-step transitions. I was thinking you might try to use an easing function with "overshoot", something like [`cubic-bezier(0, 0, 0.5, 1.20)`](https://cubic-bezier.com/#0,0,.5,1.2). Thanks for the idea, and good luck!

**Comment by lovecoding-git** [comment]
@jlmakes 
Thank you for your advice!
