### ISSUE TITLE
Reveal elements when scrolling horizontally, possible?

### ISSUE THREAD

**Issue by greenm1nd3d** [jlmakes/scrollreveal#529]
I have a 1000px wide container, "with overflow: hidden". Inside the container, I have a UL with 4 LI, and each list item is 500px wide. Each list item has pictures and text in it. If I scroll from left to right (or vise versa), I want each LI (and its contents) to be revealed as they enter the view. I can only make scrollreveal work for vertical scrolling, but not horizontal scrolling.

**Comment by jlmakes** [comment]
You must change the [`options.container`](https://scrollrevealjs.org/api/container.html) if you're scrolling a custom element, after which you should have no problem revealing elements scrolling horizontally.

**Comment by jlmakes** [comment]
You must change the [`options.container`](https://scrollrevealjs.org/api/container.html) to the 1000px wide container element you're scrolling (instead of the body). After doing so you should have no problem revealing elements scrolling horizontally.
