### ISSUE TITLE
Option to disable delay on mobile

### ISSUE THREAD

**Issue by plantage** [jlmakes/scrollreveal#53]
First of all, a big thanks! Great work Julian! My question... could there be a way to lose the delay when viewed on mobile. On a site I used scrollReveal with 3 columns and delay. Viewed on a mobile when only one item shows at a time (not in columns but underneath eachother) the delay becomes annoying. Maybe with a css class?

**Comment by petravicius** [comment]
This seems to be gone with v3. Also I mobile: true/false settings seem to only work in defaults settings, but doesn't work on separate sets. 
I'd like to either be able to disable delay on mobile devices or to disable on mobile reveal on some sets and have it working on others.
