### ISSUE TITLE
Reset scrollReveal with trigger

### ISSUE THREAD

**Issue by anta199** [jlmakes/scrollreveal#532]
Hello,
Is there a way to restart scroll reveal animations using a trigger?

I'm using the library to animate items in a modal.
It works fine with the first opening but after that, the animation doesn't work anymore until i scroll down ( I have the reset option activated).

I'm wondering if would be possible to initiate the library again after opening the modal.

Thanks

**Comment by jlmakes** [comment]
Hey @anta199 you could try calling [ScrollReveal().clean(...)](https://scrollrevealjs.org/api/clean.html) to remove the  elements from ScrollReveal when the modal is closed. Unfortunately, ScrollReveal isn't yet designed for more discrete actions and manual triggers — so I admit it's a slightly clunky potential solution.

I am working to make use cases like this simpler and more reliable in ScrollReveal 5.

**Comment by jlmakes** [comment]
Hey @anta199 you could try calling [ScrollReveal().clean(...)](https://scrollrevealjs.org/api/clean.html) to remove the  elements from ScrollReveal after the modal is closed. You should then be able to reveal them again as if it were the first time. (I'm working on making use cases like this simpler and more robust in ScrollReveal 5.)

**Comment by jlmakes** [comment]
Hey @anta199 you could try using [options.cleanup](https://scrollrevealjs.org/api/cleanup.html) (or manually calling [ScrollReveal().clean(...)](https://scrollrevealjs.org/api/clean.html)) to remove the elements from ScrollReveal after the modal is closed. You should then be able to reveal them again as if it were the first time. (I'm working on making use cases like this simpler and more robust in ScrollReveal 5.)
