### ISSUE TITLE
Distance and origin parameter not working on spans

### ISSUE THREAD

**Issue by hrvstr** [jlmakes/scrollreveal#533]
I tried searching the GitHub issues but couldn't find anything relevant. Sorry if I missed something. 

I am trying to animate a `span` but for some reason it will not apply the `distance` and `origin` parameter. Is it because a `span` is an inline element? When I change it to a `div` everything works as expected.

[span demo](https://jsbin.com/xegobuh/edit?html,output)
[div demo](https://jsbin.com/jimayun/edit?html,output)

### Environment

* Operating System: macOS 11.2.3 (20D91)
* Browser Version: 
  * Safari Version 14.0.3 (16610.4.3.1.7)
  * Firefox 86.0.1 (64-Bit)
* ScrollReveal Version: 4.0.9

**Comment by jlmakes** [comment]
This is a great question, thanks @hrvstr.

According to https://drafts.csswg.org/css-transforms/#transformable-element
> A transformable element is an element in one of these categories:
> * all elements whose layout is governed by the CSS box model except for **non-replaced inline boxes**, table-column boxes, and table-column-group boxes [CSS2],
> 
> * all SVG paint server elements, the clipPath element and SVG renderable elements with the exception of any descendant element of text content elements [SVG2].

So looks like you were spot on, inline elements generally aren't "transformable elements."

**Comment by jlmakes** [comment]
This is a great question, thanks @hrvstr.

According to https://drafts.csswg.org/css-transforms/#transformable-element
> A transformable element is an element in one of these categories:
> * all elements whose layout is governed by the CSS box model except for **non-replaced inline boxes**, table-column boxes, and table-column-group boxes [CSS2],
> 
> * all SVG paint server elements, the clipPath element and SVG renderable elements with the exception of any descendant element of text content elements [SVG2].

So looks like you were spot on: non-replaced inline elements aren't "transformable elements."
(However some are, such as `img` which is a replaced element. Here's a [list of replaced elements](https://developer.mozilla.org/en-US/docs/Web/CSS/Replaced_element).)

**Comment by hrvstr** [comment]
Thanks for the in depth answer and links. Looks like I have to change the templates of the theme I am using quite a bit.
