### ISSUE TITLE
SSL certificate for scrollrevealjs.org expired 2021-08-23

### ISSUE THREAD

**Issue by ashleedawg** [jlmakes/scrollreveal#542]
SSL certificate for https://scrollrevealjs.org expired 2021-08-23

![image](https://user-images.githubusercontent.com/29980309/132977595-ececd709-0f01-469b-9537-e78ded15fa79.png)

**Comment by jlmakes** [comment]
Thanks for the heads up! I'll get this sorted out.

**Comment by jlmakes** [comment]
Just had to update certbot :) Thanks again @ashleedawg
