### ISSUE TITLE
Reveal only when scrolling down?

### ISSUE THREAD

**Issue by jayeshtharani** [jlmakes/scrollreveal#59]
I want to animate the objects when the scrolling is towards down from the top of the page.
I don't to animate the objects when scrolling is done from bottom to top of the page.

``` js
var lastScrollTop = 0;

jQuery( window ).scroll(function( event ){

  var st = jQuery( this ).scrollTop();

  if ( st > lastScrollTop ) var isreset = true;
  else                      var isreset = false;

  lastScrollTop = st;

  var config = {
    after: '0s',
    enter: 'bottom',
    move: '24px',
    over: '0.66s',
    easing: 'ease-in-out',
    viewportFactor: 0.30,
    reset: isreset,
    init: false
  };

  window.scrollReveal = new scrollReveal( config );
  scrollReveal.init();  
});
```

But it's not working.

How can i achieve this kind of scenario ?

Thanks in advance.

**Comment by Orsey** [comment]
Hello, I found how do this : don't to animate the objects when scrolling is done from bottom to top of the page.

In file scrollReveal.js in string 228-233 you most comment this code:

     if (!this.isElementInViewport(el, this.options.viewportFactor)) {
        if (this.options.reset) {
          el.setAttribute('style', style + css.initial + css.reset);
        }
        return;

**Comment by madebylux** [comment]
Hello,

Thanks for your enquiry!

I'm now out of the office until Monday 29th June.

For urgent web hosting support, please call 0113 3185277, otherwise I will get back to you on my return.

Warm regards,
James

Lux Digital Ltd
e: james@madebylux.com
m: 07734 467977
w: www.madebylux.com
t: 0113 318 5277
a: Tower Works, Globe Road, Leeds LS11 5QG

**Comment by rascii** [comment]
This should be added as an option.
