### ISSUE TITLE
Trigger on button click

### ISSUE THREAD

**Issue by cardeo** [jlmakes/scrollreveal#64]
Hi, just wondering if it's possible to have the scroll triggered on a button click. So by default loads say 10 items/rows. On button click, loads 10 more, etc...

**Comment by divljak** [comment]
Is there any example on this?

**Comment by jlmakes** [comment]
Not sure why this was closed prematurely, but at the time it was asked—it was not possible.

The latest version of ScrollReveal @divljak however, will have more flexibility. It should be as simple as calling `sr.reveal()` inside the clear handler; the documentation for [Asynchronous Content](https://github.com/jlmakes/scrollreveal.js#35-asynchronous-content) shows how you can use `sr.sync()` to reveal any new elements found in the DOM that match previously revealed selectors.

So depending on your particular use case, calling `sr.reveal()` or `sr.sync()` inside the click handler, should get you pretty close.
