### ISSUE TITLE
fullPage.js and scrollReveal.js

### ISSUE THREAD

**Issue by djmtype** [jlmakes/scrollreveal#84]
I realize this issue was closed. [https://github.com/julianlloyd/scrollReveal.js/issues/45](https://github.com/julianlloyd/scrollReveal.js/issues/45) But curious, if anyone has gotten both to play together. Is there a special callback function needed? I can get [scrollReveal](http://scrollrevealjs.org/) to load on the initial panel. But, navigating to any other sections with [fullPage.js](http://alvarotrigo.com/fullPage/) does not work with scrollReveal or similar animated plugins for that matter.

_Whoops, I meant to post this on the fullpage.js thread._

**Comment by alvarotrigo** [comment]
@djmtype you can use it together with fullPage.js if you initialize it in the `afterRender` callback and if you make use of the `scrollBar:true` option or otherwise use the `autoScrolling:false`.

From the [fullPage.js FAQ](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions#parallax-doesnt-work-with-fullpagejs):

>  fullPage.js doesn't actually scroll the site but it changes the top or translate3d property of the site. Only when using the fullPage.js option scrollBar:true or autoScrolling:false it will actually scroll the site in a way it is accessible for the scrollTop property.

**Comment by julianlloyd** [comment]
:+1:

**Comment by githubutilities** [comment]
Thanks, it works! But each time when I use `new scrollReveal()`, after scroll 2 or 3 page, scrollReveal will stop working.

**Comment by alvarotrigo** [comment]
@githubutilities I don't know about scrollReveal, I'm afraid I can not help you on that. Maybe if you post a link to your site or are able to reproduce it somewhere.

**Comment by githubutilities** [comment]
here is the [source link](https://github.com/githubutilities/web_presentation/blob/master/index.html)

**Comment by githubutilities** [comment]
And the [sample site](http://gzmlgb2014.sinaapp.com/slide)

**Comment by githubutilities** [comment]
Notice the 3 and 4 page does not show up because of the scrollReveal.

**Comment by alvarotrigo** [comment]
I quote myself:
> you can use it together with fullPage.js if you initialize it in the afterRender callback

You are not doing it... you are using other callback which makes no sense. Its initializating it multiple times...

**Comment by githubutilities** [comment]
My mistake. Thanks.

**Comment by githubutilities** [comment]
when setting `scrollBar:true`, the autoScrolling feature will lost in mobile devices.

**Comment by rayliao** [comment]
````
if(direction=='down'){
                            if(index+1 <= $('#dowebok').find('.section').length){
                                $(this).context.sr = new scrollReveal({viewport:  $('#dowebok').find('.section').eq(index)[0].lastElementChild})
                            }
                        }else if(direction == 'up'){
                            if(index - 1 >= 1){
                                $(this).context.sr = new scrollReveal({viewport:  $('#dowebok').find('.section').eq(index-1)[0].lastElementChild})
                               
                            }
                        }
onLeave:function(index, nextIndex, direction){
                        if(direction=='down'){
                            if(index+1 <= $('#dowebok').find('.section').length){
                                $(this).context.sr = new scrollReveal({viewport:  $('#dowebok').find('.section').eq(index)[0].lastElementChild})
                            }
                        }else if(direction == 'up'){
                            if(index - 1 >= 1){
                                $(this).context.sr = new scrollReveal({viewport:  $('#dowebok').find('.section').eq(index-1)[0].lastElementChild})
                               
                            }
                        }
                    }
````

**Comment by jlmakes** [comment]
Updating @rayliao’s answer for 3.0
```js
onLeave:function(index, nextIndex, direction){
  if(direction=='down'){
    if(index+1 <= $('#dowebok').find('.section').length){
     $(this).context.sr = ScrollReveal({ container: $('#dowebok').find('.section').eq(index)[0].lastElementChild});
    }
  } else if(direction == 'up'){
    if(index - 1 >= 1){
      $(this).context.sr = ScrollReveal({ container:  $('#dowebok').find('.section').eq(index-1)[0].lastElementChild});
    }
  }
}
```
