### ISSUE TITLE
scroll reveal deleting all other injected style

### ISSUE THREAD

**Issue by Paul-Browne** [jlmakes/scrollreveal#88]
When I use scrollReveal on a `<div>` that has some style injected into it via another plugin, it gets deleted, even though scrollReveal's injected style attributes are different to the other plugins injected style attribs.
It's not an urgent problem, since I can just create a empty `<div>` and add the `data-sr` to it instead.

Basically I would like to be able to write...

``` html
<div class="d-col-1-2 d-center" data-sr="enter left">
  <!-- some content -->
</div>
```

but I have to write it like...

``` html
<div class="d-col-1-2 d-center">
  <div data-sr="enter left">
    <!-- some content -->
  </div>
</div>
```

I can't see why it's necessary for scrollReveal to delete all other injected style, but if it is, I can quite easily make do.

**Comment by julianlloyd** [comment]
If there is a style attribute present, it will preserve that value—but it will override whatever value is present at runtime.

**Comment by GeoffreyPlitt** [comment]
And there's no easy way to flag an element as "don't touch"? The problem I'm having is that SR seems to be removing styles from elements that *don't* have SR attributes on them.

**Comment by julianlloyd** [comment]
@GeoffreyPlitt SR will never touch the style attribute of an element that doesn’t have `data-sr`. You can look in the `init()` method to see how it works.

That said, it may be confusing though, because recently (see #100), SR was updated to remove `data-sr` attributes once everything is setup.
