### ISSUE TITLE
Ability to set vFactor for specific elements

### ISSUE THREAD

**Issue by thomasdashney** [jlmakes/scrollreveal#94]
Is this possible, and would it make sense for this to be? Some of my elements are quite lengthy, versus some which are small. This creates a bit of an awkward wait time for the larger ones.

**Comment by julianlloyd** [comment]
@dougmacklin @zbgecis @thomasdashney `v2.3.0` supports this!

**Comment by dougmacklin** [comment]
@julianlloyd this is awesome! great work, thanks a bunch
